#!/usr/bin/env python3
"""src/header_keys.ts must be current, and its consumers must use it.

Three hand-maintained copies of the header-key list drifted key by key; the
sweep could only DETECT that. Generation makes the TS side an artifact, so the
only remaining question is whether the artifact was regenerated.
"""
import subprocess
import sys
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
GEN = REPO / "scripts" / "gen-header-keys.py"
OUT = REPO / "src" / "header_keys.ts"


class GeneratedFileIsCurrent(unittest.TestCase):
    def test_check_mode_passes_on_the_committed_artifact(self):
        r = subprocess.run([sys.executable, str(GEN), "--check"],
                           capture_output=True, text=True, cwd=REPO)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_check_mode_FAILS_on_a_stale_artifact(self):
        """The control: a --check that cannot fail certifies nothing."""
        original = OUT.read_text()
        try:
            OUT.write_text(original.replace("\t'id',\n", "", 1))
            r = subprocess.run([sys.executable, str(GEN), "--check"],
                               capture_output=True, text=True, cwd=REPO)
            self.assertEqual(r.returncode, 1)
            self.assertIn("STALE", r.stderr)
        finally:
            OUT.write_text(original)

    def test_the_artifact_says_it_is_generated(self):
        self.assertIn("GENERATED by scripts/gen-header-keys.py", OUT.read_text())


class ConsumersDeriveRatherThanCopy(unittest.TestCase):
    def test_task_bridge_imports_it(self):
        src = (REPO / "src" / "task-bridge.ts").read_text()
        self.assertIn("from './header_keys.js'", src)
        self.assertNotIn("const _HEADER_KEYS = [", src)

    def test_conversation_server_imports_it(self):
        src = (REPO / "skills" / "phone-conversation" / "scripts"
               / "conversation-server.ts").read_text()
        self.assertIn("from '../../../src/header_keys.js'", src)
        self.assertIn("HEADER_KEY_ALTERNATION", src)


if __name__ == "__main__":
    unittest.main(verbosity=2)
