#!/usr/bin/env python3
"""src/header_keys.ts must be current, and its consumers must use it.

Three hand-maintained copies of the header-key list drifted key by key; the
sweep could only DETECT that. Generation makes the TS side an artifact, so the
only remaining question is whether the artifact was regenerated.
"""
import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
GEN = REPO / "scripts" / "gen-header-keys.py"
OUT = REPO / "src" / "header_keys.ts"


def _load():
    """In-process, so the generator's own branches are exercised and measured.

    A subprocess proves the CLI works but leaves every line inside it unseen by
    both coverage and any assertion finer than an exit code.
    """
    spec = importlib.util.spec_from_file_location("_gen_header_keys", GEN)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


class GeneratedFileIsCurrent(unittest.TestCase):
    def test_check_mode_passes_on_the_committed_artifact(self):
        self.assertEqual(_load().main(["--check"]), 0)

    def test_check_mode_FAILS_on_a_stale_artifact(self):
        """The control: a --check that cannot fail certifies nothing.

        The stale copy is a temp file, never the live artifact — a fixture that
        edits the checkout leaves it broken whenever the restore does not run.
        """
        mod = _load()
        with tempfile.TemporaryDirectory() as d:
            stale = Path(d) / "header_keys.ts"
            stale.write_text(OUT.read_text().replace("\t'id',\n", "", 1))
            mod.OUT = stale
            self.assertEqual(mod.main(["--check"]), 1)

    def test_check_mode_FAILS_when_the_artifact_is_absent(self):
        mod = _load()
        with tempfile.TemporaryDirectory() as d:
            mod.OUT = Path(d) / "never-written.ts"
            self.assertEqual(mod.main(["--check"]), 1)

    def test_write_mode_regenerates_and_then_checks_clean(self):
        mod = _load()
        with tempfile.TemporaryDirectory() as d:
            mod.OUT = Path(d) / "header_keys.ts"
            self.assertEqual(mod.main([]), 0)
            self.assertEqual(mod.OUT.read_text(), OUT.read_text())
            self.assertEqual(mod.main(["--check"]), 0)

    def test_every_python_key_reaches_the_rendered_alternation(self):
        """The point of generating: the TS side covers exactly the Python keys."""
        mod = _load()
        ks = mod.keys()
        self.assertTrue(ks)
        text = mod.render(ks)
        for k in ks:
            self.assertIn(f"\t'{k}',", text)

    def test_the_cli_entry_point_runs(self):
        """One subprocess, because __main__ is a real surface: CI calls it."""
        r = subprocess.run([sys.executable, str(GEN), "--check"],
                           capture_output=True, text=True, cwd=REPO)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)

    def test_the_artifact_says_it_is_generated(self):
        self.assertIn("GENERATED by scripts/gen-header-keys.py", OUT.read_text())


class ConsumersDeriveRatherThanCopy(unittest.TestCase):
    def test_task_bridge_imports_it(self):
        src = (REPO / "src" / "task-bridge.ts").read_text()
        self.assertIn("from './header_keys.js'", src)
        self.assertNotIn("const _HEADER_KEYS = [", src)

    def test_conversation_server_imports_it(self):
        src = (REPO / "skills" / "phone-conversation" / "scripts"
               / "conversation-server.ts").read_text()
        self.assertIn("from '../../../src/header_keys.js'", src)
        self.assertIn("HEADER_KEY_ALTERNATION", src)


if __name__ == "__main__":
    unittest.main(verbosity=2)
