#!/usr/bin/env python3
"""A refused exclude regeneration leaves the vault silently not backing up files.

`sync-workspace.sh:generate_exclude` refuses to rewrite an existing
`.git/info/exclude` that differs from the generated content (the #1445 guard
against clobbering operator-authored rules), and `_enforce_carrier_set_pre`
(`:613`) swallows the refusal so the tick continues to a successful push. The
sync reports success while the carrier set is stale.

Measured on two hosts independently before this probe existed: 65 refusals with
63 followed by `pushed to` on one host, 4/4 on the other (#2565). Nothing
surfaced it — the config IS correct, the checkout IS current, and only the
generated artifact is stale, so every existing check reads healthy. On the
second host `state/current-track.md` — the file the agent's context-reconstruct
step reads FIRST every pass — was never carried.

Two causes produce the identical symptom and need different remedies, so the
probe reports them separately:
  1. stale exclude        -> `--force-gitignore`
  2. local include REPLACES the shipped default (#2531) -> edit the local list

Run: python3 tests/health-check-carrier-set-enforced.test.py
"""
from __future__ import annotations
import importlib.util
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src" / "health-check.py"

# The whitelist shape sync-workspace.sh writes: ignore everything, un-ignore the
# carrier set. Kept minimal — the probe must not depend on the generator's exact
# formatting, which is the reason it asks git instead of diffing text.
EXCLUDE_HEAD = "# Generated by sync-workspace.sh — do not edit by hand.\n*\n"


def _load():
    spec = importlib.util.spec_from_file_location("hc_carrier_test", SRC)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _mkworkspace(tmp: Path, carrier_lines: list[str], files: list[str]) -> Path:
    ws = tmp / "workspace"
    ws.mkdir(parents=True)
    subprocess.run(["git", "init", "-q", str(ws)], check=True, capture_output=True)
    for rel in files:
        f = ws / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text("x\n")
    info = ws / ".git" / "info"
    info.mkdir(parents=True, exist_ok=True)
    (info / "exclude").write_text(EXCLUDE_HEAD + "".join(f"!{l}\n" for l in carrier_lines))
    return ws


class CarrierSetProbe(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.hc = _load()

    def tearDown(self):
        self._tmp.cleanup()

    def _patch_resolved(self, include: list[str]):
        self.hc._resolved_vault = lambda: {"sync": {"include": include}}

    def _patch_shipped(self, include: list[str]):
        root = self.tmp / "repo"
        root.mkdir(parents=True, exist_ok=True)
        (root / "sutando.config.json").write_text(
            json.dumps({"vault": {"sync": {"include": include}}})
        )
        self.hc.REPO_DIR = root

    def test_a_configured_path_that_git_still_ignores_is_REPORTED(self):
        # THE REGRESSION. Config lists state/current-track.md; the on-disk
        # exclude predates it, so git still ignores the file and the vault is
        # not backing it up. This must fail loudly, not read healthy.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r, "probe returned None on a genuinely stale carrier set")
        self.assertEqual(r["status"], "fail")
        self.assertIn("state/current-track.md", r["detail"])
        self.assertIn("--force-gitignore", r["detail"], "must name the remedy")

    def test_a_TRACKED_file_with_a_stale_exclude_is_still_reported(self):
        # The case that fooled the first version of this probe on a real host.
        # `git check-ignore` consults the index by default and reports an
        # already-tracked file as not-ignored NO MATTER WHAT the rules say. So a
        # host that carried the file once, then had its exclude go stale, read
        # healthy forever — the probe was blind to precisely the population it
        # was written for. `--no-index` is what makes the answer about the RULES.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        subprocess.run(["git", "-C", str(ws), "add", "-f", "state/current-track.md"],
                       check=True, capture_output=True)
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "fail",
                         "a tracked file with a stale exclude must still report — "
                         "check-ignore without --no-index answers about the index, not the rules")
        self.assertIn("state/current-track.md", r["detail"])

    def test_an_enforced_carrier_set_reads_ok(self):
        # Over-trigger control. If this ever fails, the probe cries wolf on every
        # healthy host and gets ignored — which is the disease, not the cure.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**", "state/", "state/current-track.md"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "ok", r.get("detail"))

    def test_the_DORMANT_override_case_is_still_caught(self):
        # The case a resolved-vs-disk comparison alone MISSES, and the reason
        # this probe has a second branch. The host's local include replaced the
        # shipped default, so the exclude legitimately matches its own resolved
        # config — nothing is stale — yet the shipped entry never arrives.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/"])                                  # local override
        self._patch_shipped(["notes/", "state/current-track.md"])          # shipped adds one
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "fail")
        self.assertIn("state/current-track.md", r["detail"])
        self.assertIn("#2531", r["detail"], "must name the override cause, not just the symptom")
        self.assertNotIn("--force-gitignore", r["detail"],
                         "forcing regenerates from the still-wrong config and looks like it worked")

    def test_an_entry_with_nothing_on_disk_is_not_evidence(self):
        # A carrier entry whose path does not exist yet must not be reported —
        # there is nothing to carry, and warning would train the reader to
        # ignore this check on every fresh workspace.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"], ["notes/a.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertEqual(r["status"], "ok", r.get("detail"))

    def test_glob_entries_resolve_to_a_real_path(self):
        # `hosts/*/` is a carrier entry on every host. A probe that cannot
        # resolve a glob silently skips the most common entry shape.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "hosts/Chis-Mac-mini/pending-questions.md"])
        self._patch_resolved(["notes/", "hosts/*/"])
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertEqual(r["status"], "fail")
        self.assertIn("hosts/*/", r["detail"], "glob entry was skipped instead of checked")

    def test_a_non_git_workspace_returns_None_not_a_failure(self):
        # Vault never initialized is a valid unconfigured state.
        ws = self.tmp / "bare"
        ws.mkdir()
        self._patch_resolved(["notes/"])
        self.assertIsNone(self.hc.check_carrier_set_enforced(workspace_dir=ws))

    def test_entries_that_resolve_to_nothing_are_skipped_cleanly(self):
        # Empty/whitespace entries and globs matching nothing must resolve to
        # None rather than raising or inventing a path.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"], ["notes/a.md"])
        self.assertIsNone(self.hc._carrier_representative(ws, ""))
        self.assertIsNone(self.hc._carrier_representative(ws, "   "))
        self.assertIsNone(self.hc._carrier_representative(ws, "nope/*/"))
        self.assertIsNone(self.hc._carrier_representative(ws, "missing.md"))
        self.assertIsNotNone(self.hc._carrier_representative(ws, "notes/"))

    def test_no_configured_include_is_not_a_finding(self):
        # A host with no carrier set configured has nothing to enforce.
        ws = _mkworkspace(self.tmp, [], [])
        self._patch_resolved([])
        self.assertIsNone(self.hc.check_carrier_set_enforced(workspace_dir=ws))

    def _with_run(self, fake):
        # Save the ORIGINAL first. `self.hc.subprocess` IS the shared module, so
        # re-importing it in the restore hands back the patched function and the
        # break leaks into every later test.
        original = self.hc.subprocess.run
        self.hc.subprocess.run = fake
        self.addCleanup(lambda: setattr(self.hc.subprocess, "run", original))

    def test_a_git_that_CANNOT_RUN_is_reported_UNKNOWN_not_healthy(self):
        # This assertion previously demanded "ok", on the reasoning that a broken
        # subprocess must not cry wolf. That was wrong, and qingyun-wu caught it:
        # an unmeasured carrier set is not a measured-healthy one, and reporting
        # green when the measurement could not run is the EXACT failure this probe
        # was written to catch — reproduced inside the probe itself.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        def boom(*a, **k):
            raise OSError("git missing")
        self._with_run(boom)
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok",
                            "a carrier set that could not be measured must not read healthy")
        self.assertIn("UNKNOWN", r["detail"])

    def test_a_git_EXIT_128_is_not_folded_in_with_exit_1(self):
        # check-ignore's contract: 0 = ignored, 1 = NOT ignored, anything else =
        # the command failed. `returncode != 0` treated 128 exactly like 1, so a
        # git that errored reported the path as carried.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        class R:
            returncode = 128
            stdout = b""
            stderr = b"fatal: not a git repository"
        self._with_run(lambda *a, **k: R())
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok", "exit 128 is a failed measurement, not a pass")
        self.assertIn("UNKNOWN", r["detail"])

    def test_it_does_NOT_spawn_a_bare_git(self):
        # On macOS /usr/bin/git is an Xcode-CLT shim that pops an install dialog
        # when the tools are absent. This probe runs from a BACKGROUND health
        # check, so nobody is there to dismiss it. Everything must go through the
        # repo's resolver, which refuses that shim rather than spawning it.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        seen = []
        class R:
            returncode = 1
            stdout = b""
            stderr = b""
        def spy(argv, *a, **k):
            seen.append(list(argv))
            return R()
        self._with_run(spy)
        self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertTrue(seen, "probe made no git call at all — the assertion proves nothing")
        for argv in seen:
            self.assertNotEqual(argv[0], "git",
                                "bare 'git' can be the CLT shim; route through git_argv")
            self.assertTrue(os.path.isabs(argv[0]),
                            f"expected a resolved absolute git path, got {argv[0]!r}")

    def test_an_unreadable_shipped_config_degrades_to_the_stale_branch_only(self):
        # Malformed/absent shipped config must not crash or fabricate a
        # "dropped by override" claim it cannot substantiate.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**", "state/", "state/current-track.md"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        bad = self.tmp / "badrepo"
        bad.mkdir(parents=True, exist_ok=True)
        (bad / "sutando.config.json").write_text("{ not json")
        self.hc.REPO_DIR = bad
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "ok", r.get("detail"))

    def test_the_probe_is_registered_in_the_run_list(self):
        # A probe nobody calls cannot report anything. This is the assertion
        # that fails if the function is added but never wired in.
        src = SRC.read_text()
        self.assertIn("check_carrier_set_enforced()", src,
                      "probe defined but never invoked from the run list")


if __name__ == "__main__":
    unittest.main(verbosity=2)
