#!/usr/bin/env python3
"""A refused exclude regeneration leaves the vault silently not backing up files.

`sync-workspace.sh:generate_exclude` refuses to rewrite an existing
`.git/info/exclude` that differs from the generated content (the #1445 guard
against clobbering operator-authored rules), and `_enforce_carrier_set_pre`
(`:613`) swallows the refusal so the tick continues to a successful push. The
sync reports success while the carrier set is stale.

Measured on two hosts independently before this probe existed: 65 refusals with
63 followed by `pushed to` on one host, 4/4 on the other (#2565). Nothing
surfaced it — the config IS correct, the checkout IS current, and only the
generated artifact is stale, so every existing check reads healthy. On the
second host `state/current-track.md` — the file the agent's context-reconstruct
step reads FIRST every pass — was never carried.

Two causes produce the identical symptom and need different remedies, so the
probe reports them separately:
  1. stale exclude        -> `--force-gitignore`
  2. local include REPLACES the shipped default (#2531) -> edit the local list

Run: python3 tests/health-check-carrier-set-enforced.test.py
"""
from __future__ import annotations
import importlib.util
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src" / "health-check.py"

# The whitelist shape sync-workspace.sh writes: ignore everything, un-ignore the
# carrier set. Kept minimal — the probe must not depend on the generator's exact
# formatting, which is the reason it asks git instead of diffing text.
EXCLUDE_HEAD = "# Generated by sync-workspace.sh — do not edit by hand.\n*\n"


def _load():
    spec = importlib.util.spec_from_file_location("hc_carrier_test", SRC)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _mkworkspace(tmp: Path, carrier_lines: list[str], files: list[str]) -> Path:
    ws = tmp / "workspace"
    ws.mkdir(parents=True)
    subprocess.run(["git", "init", "-q", str(ws)], check=True, capture_output=True)
    for rel in files:
        f = ws / rel
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text("x\n")
    info = ws / ".git" / "info"
    info.mkdir(parents=True, exist_ok=True)
    (info / "exclude").write_text(EXCLUDE_HEAD + "".join(f"!{l}\n" for l in carrier_lines))
    return ws


class CarrierSetProbe(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp = Path(self._tmp.name)
        self.hc = _load()

    def tearDown(self):
        self._tmp.cleanup()

    def _patch_resolved(self, include: list[str]):
        self.hc._resolved_vault = lambda: {"sync": {"include": include}}

    def _patch_shipped(self, include: list[str]):
        root = self.tmp / "repo"
        root.mkdir(parents=True, exist_ok=True)
        (root / "sutando.config.json").write_text(
            json.dumps({"vault": {"sync": {"include": include}}})
        )
        self.hc.REPO_DIR = root

    def test_a_configured_path_that_git_still_ignores_is_REPORTED(self):
        # THE REGRESSION. Config lists state/current-track.md; the on-disk
        # exclude predates it, so git still ignores the file and the vault is
        # not backing it up. This must fail loudly, not read healthy.
        # Uses `hosts/*/`, not `state/current-track.md`: this test is about STALE
        # DETECTION, and that path now routes to the must-not-be-carried carve-out.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "hosts/h/pending-questions.md"])
        self._patch_resolved(["notes/", "hosts/*/"])
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r, "probe returned None on a genuinely stale carrier set")
        self.assertEqual(r["status"], "fail")
        self.assertIn("hosts/*/", r["detail"])
        self.assertIn("--force-gitignore", r["detail"], "must name the remedy")

    def test_a_TRACKED_file_with_a_stale_exclude_is_still_reported(self):
        # The case that fooled the first version of this probe on a real host.
        # `git check-ignore` consults the index by default and reports an
        # already-tracked file as not-ignored NO MATTER WHAT the rules say. So a
        # host that carried the file once, then had its exclude go stale, read
        # healthy forever — the probe was blind to precisely the population it
        # was written for. `--no-index` is what makes the answer about the RULES.
        # Safe path for the same reason as above — the assertion is about
        # --no-index, not about which file is involved.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "hosts/h/pending-questions.md"])
        subprocess.run(["git", "-C", str(ws), "add", "-f", "hosts/h/pending-questions.md"],
                       check=True, capture_output=True)
        self._patch_resolved(["notes/", "hosts/*/"])
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "fail",
                         "a tracked file with a stale exclude must still report — "
                         "check-ignore without --no-index answers about the index, not the rules")
        self.assertIn("hosts/*/", r["detail"])

    def test_an_enforced_carrier_set_reads_ok(self):
        # Over-trigger control. If this ever fails, the probe cries wolf on every
        # healthy host and gets ignored — which is the disease, not the cure.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**", "state/", "state/current-track.md"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "ok", r.get("detail"))

    def test_the_DORMANT_override_case_is_still_caught(self):
        # The case a resolved-vs-disk comparison alone MISSES, and the reason
        # this probe has a second branch. The host's local include replaced the
        # shipped default, so the exclude legitimately matches its own resolved
        # config — nothing is stale — yet the shipped entry never arrives.
        # Uses `hosts/*/` rather than `state/current-track.md`: this test is about
        # the MECHANISM (a local include replacing the shipped default), not that
        # particular path, and the flat anchor now routes to the must-NOT-re-add
        # branch. Pinning the mechanism to an entry that is safe to re-add keeps
        # the two concerns from colliding again.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "hosts/somehost/pending-questions.md"])
        self._patch_resolved(["notes/"])                                  # local override
        self._patch_shipped(["notes/", "hosts/*/"])                        # shipped adds one
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "fail")
        self.assertIn("hosts/*/", r["detail"])
        self.assertIn("#2531", r["detail"], "must name the override cause, not just the symptom")
        self.assertNotIn("--force-gitignore", r["detail"],
                         "forcing regenerates from the still-wrong config and looks like it worked")

    def test_an_entry_with_nothing_on_disk_is_not_evidence(self):
        # A carrier entry whose path does not exist yet must not be reported —
        # there is nothing to carry, and warning would train the reader to
        # ignore this check on every fresh workspace.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"], ["notes/a.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertEqual(r["status"], "ok", r.get("detail"))

    def test_glob_entries_resolve_to_a_real_path(self):
        # `hosts/*/` is a carrier entry on every host. A probe that cannot
        # resolve a glob silently skips the most common entry shape.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "hosts/Chis-Mac-mini/pending-questions.md"])
        self._patch_resolved(["notes/", "hosts/*/"])
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertEqual(r["status"], "fail")
        self.assertIn("hosts/*/", r["detail"], "glob entry was skipped instead of checked")

    def test_a_non_git_workspace_returns_None_not_a_failure(self):
        # Vault never initialized is a valid unconfigured state.
        ws = self.tmp / "bare"
        ws.mkdir()
        self._patch_resolved(["notes/"])
        self.assertIsNone(self.hc.check_carrier_set_enforced(workspace_dir=ws))

    def test_entries_that_resolve_to_nothing_are_skipped_cleanly(self):
        # Empty/whitespace entries and globs matching nothing must resolve to
        # None rather than raising or inventing a path.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"], ["notes/a.md"])
        self.assertIsNone(self.hc._carrier_representative(ws, ""))
        self.assertIsNone(self.hc._carrier_representative(ws, "   "))
        self.assertIsNone(self.hc._carrier_representative(ws, "nope/*/"))
        self.assertIsNone(self.hc._carrier_representative(ws, "missing.md"))
        self.assertIsNotNone(self.hc._carrier_representative(ws, "notes/"))

    def test_no_configured_include_is_not_a_finding(self):
        # A host with no carrier set configured has nothing to enforce.
        ws = _mkworkspace(self.tmp, [], [])
        self._patch_resolved([])
        self.assertIsNone(self.hc.check_carrier_set_enforced(workspace_dir=ws))

    def _with_run(self, fake):
        # Save the ORIGINAL first. `self.hc.subprocess` IS the shared module, so
        # re-importing it in the restore hands back the patched function and the
        # break leaks into every later test.
        original = self.hc.subprocess.run
        self.hc.subprocess.run = fake
        self.addCleanup(lambda: setattr(self.hc.subprocess, "run", original))

    def test_a_git_that_CANNOT_RUN_is_reported_UNKNOWN_not_healthy(self):
        # This assertion previously demanded "ok", on the reasoning that a broken
        # subprocess must not cry wolf. That was wrong, and qingyun-wu caught it:
        # an unmeasured carrier set is not a measured-healthy one, and reporting
        # green when the measurement could not run is the EXACT failure this probe
        # was written to catch — reproduced inside the probe itself.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        def boom(*a, **k):
            raise OSError("git missing")
        self._with_run(boom)
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok",
                            "a carrier set that could not be measured must not read healthy")
        self.assertIn("UNKNOWN", r["detail"])

    def test_a_git_EXIT_128_is_not_folded_in_with_exit_1(self):
        # check-ignore's contract: 0 = ignored, 1 = NOT ignored, anything else =
        # the command failed. `returncode != 0` treated 128 exactly like 1, so a
        # git that errored reported the path as carried.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        class R:
            returncode = 128
            stdout = b""
            stderr = b"fatal: not a git repository"
        self._with_run(lambda *a, **k: R())
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok", "exit 128 is a failed measurement, not a pass")
        self.assertIn("UNKNOWN", r["detail"])

    def test_it_does_NOT_spawn_a_bare_git(self):
        # On macOS /usr/bin/git is an Xcode-CLT shim that pops an install dialog
        # when the tools are absent. This probe runs from a BACKGROUND health
        # check, so nobody is there to dismiss it. Everything must go through the
        # repo's resolver, which refuses that shim rather than spawning it.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        seen = []
        class R:
            returncode = 1
            stdout = b""
            stderr = b""
        def spy(argv, *a, **k):
            seen.append(list(argv))
            return R()
        self._with_run(spy)
        self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertTrue(seen, "probe made no git call at all — the assertion proves nothing")
        for argv in seen:
            self.assertNotEqual(argv[0], "git",
                                "bare 'git' can be the CLT shim; route through git_argv")
            self.assertTrue(os.path.isabs(argv[0]),
                            f"expected a resolved absolute git path, got {argv[0]!r}")

    def test_an_unreadable_shipped_config_degrades_to_the_stale_branch_only(self):
        # Malformed/absent shipped config must not crash or fabricate a
        # "dropped by override" claim it cannot substantiate.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**", "state/", "state/current-track.md"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        bad = self.tmp / "badrepo"
        bad.mkdir(parents=True, exist_ok=True)
        (bad / "sutando.config.json").write_text("{ not json")
        self.hc.REPO_DIR = bad
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "ok", r.get("detail"))

    def test_the_KNOWN_UNSAFE_entry_is_reported_but_never_recommended(self):
        # qingyun-wu, P1 on e73e2597. The remedy said "add them to the local list"
        # for EVERY missing shipped entry — including `state/current-track.md`,
        # which #2534 ships at a flat, SHARED vault path. Following that advice
        # re-tracks per-host state at a path a peer also writes, which is exactly
        # the incident that destroyed a peer's 1056-line anchor on 2026-08-03.
        #
        # It must still be REPORTED — silently filtering it would hide a real
        # divergence, which is the failure this whole probe exists to prevent.
        # What had to go is the instruction, not the information.
        #
        # The exclude must NOT un-ignore `state/current-track.md` here. This fixture
        # originally did, which made the entry carried BY OUTCOME while the test
        # asserted it was dropped — it only passed because the dropped branch
        # compared config strings and never looked at disk. Once that branch asks
        # git (#2571), an over-specified fixture like that stops describing the
        # state it claims to test.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/"])                                   # host dropped it
        self._patch_shipped(["notes/", "state/current-track.md"])          # shipped still has it
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "fail")
        self.assertIn("state/current-track.md", r["detail"], "must still be reported")
        self.assertIn("must NOT be re-added", r["detail"])
        self.assertIn("#2567", r["detail"], "must name why")
        self.assertNotIn("add them to the local list", r["detail"],
                         "the data-loss instruction must not accompany this entry")

    def test_a_BROADER_local_entry_is_coverage_not_a_dropped_entry(self):
        # #2571, reported by Sutando-Pro against #2566 within minutes of merge.
        # Their host's local config carries `hosts/` where the shipped default says
        # `hosts/*/` — strictly BROADER, and the whole subtree is demonstrably
        # carried. The dropped branch compared strings, so it reported `hosts/*/`
        # missing and advised "add them to the local list", i.e. told the operator
        # to narrow a config that was already right.
        #
        # The irony is the point: this probe exists to catch "config claims carried,
        # reality says not". This is the inverse — reality says carried, the config
        # string says not — and it fired anyway.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**", "hosts/", "hosts/**"],
                          ["notes/a.md", "hosts/h/current-track.md"])
        self._patch_resolved(["notes/", "hosts/"])       # broader than shipped
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "ok",
                         "a broader local rule carries the subtree; nothing is dropped")
        self.assertNotIn("hosts/*/", r["detail"])
        self.assertNotIn("add them to the local list", r["detail"])

    def test_a_NARROWER_local_rule_covering_one_child_is_not_coverage(self):
        # qingyun-wu P1 on #2572. `_carrier_representative` returned the FIRST
        # glob match, so a shipped wildcard matching several paths was judged on
        # one sampled witness. A narrower local rule covers one child while its
        # siblings stay ignored — and if the sample landed on the covered child,
        # the probe reported the vault healthy with a whole host subtree unbacked.
        #
        # This is the exact inverse of the case the previous test pins, and one
        # host cannot tell them apart: with a single match, first-hit coverage and
        # full coverage are indistinguishable. Two hosts is the minimum fixture
        # that can fail.
        #
        # The `!hosts/` line is load-bearing. gitignore cannot re-include a path
        # whose PARENT directory is excluded, so `!hosts/a/` under a leading `*`
        # leaves hosts/a ignored too — and the first cut of this fixture did
        # exactly that, making BOTH hosts ignored. The assertion still passed,
        # because first-hit sampling then landed on an ignored path and reported
        # it dropped for the right verdict via the wrong mechanism. A fixture that
        # passes at the broken head is not a witness.
        ws = _mkworkspace(self.tmp,
                          ["notes/", "notes/**",
                           "hosts/", "hosts/a/", "hosts/a/**"],   # carries a, NOT b
                          ["notes/x.md", "hosts/a/current-track.md", "hosts/b/current-track.md"])
        self._patch_resolved(["notes/", "hosts/a/"])     # narrower than shipped
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok",
                            "hosts/b is ignored and unbacked — sampling hosts/a must not pass it")
        self.assertIn("hosts/*/", r["detail"])

    def test_a_measurement_failure_never_erases_findings(self):
        # qingyun-wu P1 on #2572, and the sharper half: the code said one thing
        # and did the other. A comment promised a failed measurement "keeps being
        # reported", while the enclosing `except` reset `dropped = []` — so one
        # entry's git timeout erased findings already collected and returned ok.
        # Fail-OPEN in the probe whose entire purpose is catching silent
        # non-backup.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/x.md", "data/f.md"])
        self._patch_resolved(["notes/"])
        self._patch_shipped(["notes/", "data/"])
        real = self.hc.subprocess.run

        def flaky(argv, *a, **kw):
            # Succeed for the resolved entry's stale-branch probe, fail only on
            # the shipped entry's coverage probe — the exact mixed case where the
            # old code discarded the finding it already had.
            if any("data" in str(x) for x in argv):
                raise self.hc.subprocess.SubprocessError("timed out")
            return real(argv, *a, **kw)

        self.hc.subprocess.run = flaky
        try:
            r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        finally:
            self.hc.subprocess.run = real
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok",
                            "a measurement that failed is UNKNOWN, never a pass")
        self.assertIn("data/", r["detail"], "the entry we could not measure must be named")

    def test_an_ODD_EXIT_CODE_is_also_unmeasured_not_covered(self):
        # The other half of "the measurement failed", and a separate line: the
        # test above makes check-ignore RAISE, this makes it RETURN an exit code
        # that is neither 0 (ignored) nor 1 (not ignored) — a git that ran and
        # could not answer, e.g. 128 on a broken repo.
        #
        # Worth its own case because the tempting shape is `if rc != 0: covered`,
        # which silently folds 128 in with 1 and reports a path as carried on the
        # strength of a failed read. That is the same defect this probe exists to
        # catch, and #2566 shipped it in the stale branch before review found it.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/x.md", "data/f.md"])
        self._patch_resolved(["notes/"])
        self._patch_shipped(["notes/", "data/"])
        real = self.hc.subprocess.run

        class _Odd:
            returncode = 128
            stdout = b""
            stderr = b"fatal: not a git repository"

        def odd_exit(argv, *a, **kw):
            if any("data" in str(x) for x in argv):
                return _Odd()
            return real(argv, *a, **kw)

        self.hc.subprocess.run = odd_exit
        try:
            r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        finally:
            self.hc.subprocess.run = real
        self.assertIsNotNone(r)
        self.assertNotEqual(r["status"], "ok",
                            "exit 128 is a git that could not answer, not a pass")
        self.assertIn("data/", r["detail"])

    def test_a_shipped_entry_with_nothing_on_disk_is_still_reported(self):
        # The coverage test can only speak when something is materialized. An entry
        # the local config omits and that has NOTHING under it yet has no outcome to
        # measure — but the divergence is real and turns into silent data loss the
        # moment the first file lands there. Report it rather than let "no evidence
        # of harm yet" read as covered.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"], ["notes/a.md"])
        self._patch_resolved(["notes/"])
        self._patch_shipped(["notes/", "data/"])         # data/ does not exist yet
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertIn("data/", r["detail"])
        self.assertIn("add them to the local list", r["detail"])

    def test_a_SAFE_dropped_entry_still_gets_the_add_it_remedy(self):
        # Over-trigger control: the unsafe carve-out must not swallow the ordinary
        # #2531 case, which is the reason the dropped branch exists at all.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"], ["notes/a.md", "hosts/h/x.md"])
        self._patch_resolved(["notes/"])
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertIn("hosts/*/", r["detail"])
        self.assertIn("add them to the local list", r["detail"])
        self.assertNotIn("must NOT be re-added", r["detail"])

    def test_an_UNSAFE_path_that_is_NOT_carried_is_not_a_failure(self):
        # Found by running the merged probe on a live host. That host had
        # deliberately un-carried `state/current-track.md` to stop overwriting a
        # peer's anchor — the RIGHT state — and the probe reported `fail` with the
        # remedy `--force-gitignore`, i.e. the exact command that re-carries it and
        # resumes the cross-host overwrite.
        #
        # #2566 gave the dropped branch this carve-out; the stale branch never got
        # it. Here it must move the verdict off `fail` — not carrying a path that
        # must not be carried is not a failure.
        #
        # But NOT to `ok` either (qingyun-wu, #2570): this host is only right
        # because it DIVERGED from the shipped default, which still lists the flat
        # path and still re-carries it in a fresh workspace. `warn` is the honest
        # level — visible, but `main()` excludes it from `issues`, so it neither
        # alerts nor reaches the --fix loop that would re-add the path.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "warn",
                         "correct on this host, but the shipped default still re-carries it")
        self.assertIn("correctly NOT carried", r["detail"])
        # The detail must name the DEFAULT as the thing still unsafe, or the warn
        # reads as a local nit rather than a live gap in the shipped contract.
        self.assertIn("default", r["detail"])
        # The command name legitimately appears as a PROHIBITION ("do not
        # `--force-gitignore` it back"). Asserting its mere absence would forbid
        # the warning as well as the instruction — what must never appear is the
        # INSTRUCTIONAL form the stale branch hands out.
        self.assertIn("do not `--force-gitignore`", r["detail"])
        self.assertNotIn("fix with `bash scripts/sync-workspace.sh --force-gitignore`", r["detail"],
                         "must never hand back the command that resumes the overwrite")

    def _carve_out_result(self):
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "state/current-track.md"])
        self._patch_resolved(["notes/", "state/current-track.md"])
        self._patch_shipped(["notes/", "state/current-track.md"])
        return self.hc.check_carrier_set_enforced(workspace_dir=ws)

    def test_the_UNSAFE_carve_out_stays_out_of_the_issues_list(self):
        # Necessary but NOWHERE NEAR sufficient — see the three tests below. This
        # only pins that the summary/--fix path treats it as a non-issue.
        r = self._carve_out_result()
        self.assertIn(r["status"], ("ok", "warn"))

    def test_the_carve_out_does_not_EMIT_A_TASK(self):
        # The first version of this carve-out asserted "never alerts" and tested
        # main()'s local `issues` list — which is not what alerts. `--emit-task`
        # consumes the FULL checks list and counted a plain warn as a failure, so
        # the state still queued a task for the agent (qingyun-wu, #2570).
        # Exercise the helper itself.
        r = self._carve_out_result()
        tasks = self.tmp / "emit-tasks"
        tasks.mkdir(exist_ok=True)
        self.hc.emit_task_for_failures(
            [r], state_file=self.tmp / "emit-state.json", tasks_dir=tasks)
        self.assertEqual(sorted(p.name for p in tasks.glob("*.txt")), [],
                         "a non-actionable transitional state must not queue owner work")

    def test_the_carve_out_does_not_NOTIFY_or_reach_the_owner_DM(self):
        # notify_for_failures shells out to osascript; record the invocation
        # instead of firing a real notification at whoever runs the suite. It
        # also writes its dedup state file only when it actually alerts, so the
        # absence of that file is a second, independent witness.
        r = self._carve_out_result()
        calls = []
        real_run = self.hc.subprocess.run
        self.hc.subprocess.run = lambda *a, **kw: calls.append(a) or real_run(
            ["/usr/bin/true"], capture_output=True)
        state = self.tmp / "notify-state.json"
        try:
            self.hc.notify_for_failures([r], state_file=state)
        finally:
            self.hc.subprocess.run = real_run
        self.assertEqual(calls, [], "a suppressed check must not fire a notification")
        self.assertFalse(state.exists(), "and must not record an alert transition")
        self.assertNotIn(r, self.hc._slack_failures([r]),
                         "nor reach the remote owner DM")

    def test_an_ORDINARY_warn_still_alerts(self):
        # Over-trigger control. The suppression must be narrow: if it muted every
        # warn, this fix would trade a false page for a silent failure, which is
        # strictly worse in a probe whose job is catching silent non-backup.
        ordinary = {"name": "something-else", "status": "warn", "detail": "a real problem"}
        tasks = self.tmp / "ordinary-tasks"
        tasks.mkdir(exist_ok=True)
        self.hc.emit_task_for_failures(
            [ordinary], state_file=self.tmp / "ordinary-state.json", tasks_dir=tasks)
        self.assertEqual(len(list(tasks.glob("*.txt"))), 1,
                         "an ordinary warn must still reach the owner")
        self.assertIn(ordinary, self.hc._slack_failures([ordinary]))

    def test_suppression_requires_an_explicit_False(self):
        # A missing key must alert, so no existing check changes behavior by
        # omission and a typo cannot silence a real failure.
        self.assertFalse(self.hc._alerts_suppressed({"status": "warn"}))
        self.assertFalse(self.hc._alerts_suppressed({"status": "warn", "alerting": True}))
        self.assertTrue(self.hc._alerts_suppressed({"status": "warn", "alerting": False}))

    def test_a_genuinely_stale_SAFE_path_still_fails_with_its_remedy(self):
        # Over-trigger control. The carve-out must not blind the stale branch to
        # the case the whole probe exists for.
        ws = _mkworkspace(self.tmp, ["notes/", "notes/**"],
                          ["notes/a.md", "hosts/h/pending-questions.md"])
        self._patch_resolved(["notes/", "hosts/*/"])
        self._patch_shipped(["notes/", "hosts/*/"])
        r = self.hc.check_carrier_set_enforced(workspace_dir=ws)
        self.assertIsNotNone(r)
        self.assertEqual(r["status"], "fail")
        self.assertIn("hosts/*/", r["detail"])
        self.assertIn("--force-gitignore", r["detail"], "the real remedy must survive")

    def test_the_probe_is_registered_in_the_run_list(self):
        # A probe nobody calls cannot report anything. This is the assertion
        # that fails if the function is added but never wired in.
        src = SRC.read_text()
        self.assertIn("check_carrier_set_enforced()", src,
                      "probe defined but never invoked from the run list")


if __name__ == "__main__":
    unittest.main(verbosity=2)
