#!/bin/bash
# Tests for the --visible launch flag in src/agent/claude/cli/start-cli.sh
# (sonichi#2410): flag parse + open_visible_terminal wiring exist at both call
# sites (structure assertions, matching the startup-*-wireup test pattern), and
# the generator block — mirrored here exactly — writes an executable .command
# that attaches to the right socket/session (behavior assertion, no GUI needed;
# `open` is NOT invoked in this test).
#
# Run: bash tests/start-cli-visible.test.sh   (exit 0 pass, 1 fail)
set -u

REPO="$(cd "$(dirname "$0")/.." && pwd)"
LAUNCHER="$REPO/src/agent/claude/cli/start-cli.sh"
CODEX_LAUNCHER="$REPO/src/agent/codex/cli/start-cli.sh"
fails=0
say() { echo "$1  $2"; if [ "$1" = "FAIL" ]; then fails=$((fails+1)); fi; return 0; }

# --- structure: flag + helper + both call sites present ---
grep -q 'VISIBLE=1' "$LAUNCHER" && grep -q -- '--visible' "$LAUNCHER" \
  && say ok "flag parse present" || say FAIL "flag parse missing"
grep -q 'open_visible_terminal()' "$LAUNCHER" \
  && say ok "helper defined" || say FAIL "helper missing"
n_calls=$(grep -c '^\s*open_visible_terminal$' "$LAUNCHER")
[ "$n_calls" -eq 2 ] \
  && say ok "helper called at both call sites (already-running + fresh-start)" \
  || say FAIL "expected 2 call sites, found $n_calls"
grep -q 'open -a Terminal "\$cmdfile"' "$LAUNCHER" \
  && say ok "opens via open -a Terminal (TCC-free path)" || say FAIL "open call missing"
grep -q 'uname)" = "Darwin"' "$LAUNCHER" \
  && say ok "Darwin-guarded" || say FAIL "missing Darwin guard"

# --- runtime parity (#2412 review): the codex adapter carries the SAME contract ---
grep -q 'VISIBLE=1' "$CODEX_LAUNCHER" && grep -q 'open_visible_terminal()' "$CODEX_LAUNCHER" \
  && say ok "codex adapter: flag + helper present" || say FAIL "codex adapter missing flag/helper"
n=$(grep -c '^\s*open_visible_terminal$' "$CODEX_LAUNCHER")
[ "$n" -eq 2 ] && say ok "codex adapter: both call sites" || say FAIL "codex adapter call sites: $n"
grep -q "exec tmux -S '\$TMUX_SOCKET' attach -t '\$SESSION'" "$CODEX_LAUNCHER" \
  && say ok "codex adapter: generator matches contract" || say FAIL "codex generator drifted"

# --- behavior: mirrored generator block against a temp workspace ---
TMUX_SOCKET="/tmp/test-visible.sock"
SESSION="sutando-core"
ws="$(mktemp -d)"
mkdir -p "$ws/state"
cmdfile="$ws/state/attach-core.command"
{
  echo '#!/bin/bash'
  echo '# Auto-generated by start-cli.sh --visible (sonichi#2410) — attaches this'
  echo '# Terminal window to the core session. Safe to re-run; delete freely.'
  echo "exec tmux -S '$TMUX_SOCKET' attach -t '$SESSION'"
} > "$cmdfile"
chmod +x "$cmdfile"
[ -x "$cmdfile" ] && say ok "generated .command is executable" || say FAIL "not executable"
grep -q "tmux -S '/tmp/test-visible.sock' attach -t 'sutando-core'" "$cmdfile" \
  && say ok ".command attaches to the exact socket+session" || say FAIL "wrong attach line"
bash -n "$cmdfile" && say ok ".command is valid bash" || say FAIL ".command syntax error"
# mirror-drift guard: the generator lines in the launcher must match this mirror
grep -q "exec tmux -S '\$TMUX_SOCKET' attach -t '\$SESSION'" "$LAUNCHER" \
  && say ok "launcher generator matches mirrored block" || say FAIL "generator drifted from mirror"
rm -rf "$ws"

echo
if [ $fails -gt 0 ]; then echo "$fails test(s) FAILED"; exit 1; fi
echo "all tests passed — start-cli --visible contract"
