#!/usr/bin/env bash
# An owned built-in deny must be adoptable regardless of the operator's
# carve-out config: `vault.sync.exclude: []` is supported, and gating the
# script's own snap-temp deny on it leaves an upgraded workspace staging the
# very temp the rule exists to hide.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
TEST_ROOT="$(mktemp -d -t sync-empty-exclude-test.XXXXXX)"
trap 'rm -rf "$TEST_ROOT"' EXIT

pass=0
fail=0
check() {
    local description="$1"
    shift
    if "$@" >/dev/null 2>&1; then
        echo "OK: $description"
        pass=$((pass + 1))
    else
        echo "FAIL: $description"
        fail=$((fail + 1))
    fi
}
refute() {
    local description="$1"
    shift
    if "$@" >/dev/null 2>&1; then
        echo "FAIL: $description"
        fail=$((fail + 1))
    else
        echo "OK: $description"
        pass=$((pass + 1))
    fi
}

FIXTURE_ROOT="$TEST_ROOT/empty-exclude"
FIXTURE_REPO="$FIXTURE_ROOT/repo"
FIXTURE_WS="$FIXTURE_ROOT/workspace"
FIXTURE_VAULT="$FIXTURE_ROOT/vault.git"
mkdir -p "$FIXTURE_REPO/scripts" "$FIXTURE_REPO/src"
cp "$REPO/scripts/sync-workspace.sh" "$FIXTURE_REPO/scripts/"
cp "$REPO/scripts/sutando-config.sh" "$FIXTURE_REPO/scripts/"
cp "$REPO/scripts/python-binary.sh" "$FIXTURE_REPO/scripts/"
cp "$REPO/src/sutando_config.py" "$FIXTURE_REPO/src/"
touch "$FIXTURE_REPO/CLAUDE.md"
mkdir -p "$FIXTURE_REPO/skills"
git init -q "$FIXTURE_REPO"
git init -q --bare "$FIXTURE_VAULT"

# The shipped config with the operator's carve-out list EMPTIED — the
# supported shape this regression exists for.
python3 - "$REPO/sutando.config.json" "$FIXTURE_REPO/sutando.config.json" <<'PY'
import json, sys
cfg = json.load(open(sys.argv[1]))
cfg["vault"]["sync"]["exclude"] = []
json.dump(cfg, open(sys.argv[2], "w"), indent=2)
PY

check "fixture config really has an empty carve-out list (control)" \
    python3 -c "
import json, sys
exc = json.load(open('$FIXTURE_REPO/sutando.config.json'))['vault']['sync']['exclude']
sys.exit(0 if exc == [] else 1)
"

mkdir -p "$FIXTURE_WS/hosts/empty-host" "$FIXTURE_WS/notes"
printf 'a note\n' > "$FIXTURE_WS/notes/a.md"
cat > "$FIXTURE_REPO/sutando.config.local.json" <<JSON
{"workspace": {"path": "$FIXTURE_WS"}}
JSON

SYNC="$FIXTURE_REPO/scripts/sync-workspace.sh"
SYNC_ENV=(
    SUTANDO_HOST_OVERRIDE=empty-host
    SUTANDO_WS_ID_OVERRIDE=empty1
    SUTANDO_SYNC_LOCK_DIR="$FIXTURE_ROOT/sync.lock"
    GIT_AUTHOR_NAME="Empty Exclude Test"
    GIT_AUTHOR_EMAIL="empty-exclude@example.com"
    GIT_COMMITTER_NAME="Empty Exclude Test"
    GIT_COMMITTER_EMAIL="empty-exclude@example.com"
)
env "${SYNC_ENV[@]}" bash "$SYNC" \
    --vault-url "$FIXTURE_VAULT" --force-gitignore --init \
    >/dev/null 2>&1 || true

RULES="$FIXTURE_WS/.git/info/exclude"
DENY='hosts/*/build_log.md.snap.??????'

check "fresh generation emits the built-in deny even with empty carve-outs" \
    grep -qFx "$DENY" "$RULES"

# The upgrade shape: a file generated by an older version — identical except
# the built-in deny had not been invented yet.
grep -vFx "$DENY" "$RULES" > "$RULES.older" && mv "$RULES.older" "$RULES"
refute "older generated file lacks the deny (setup control)" \
    grep -qFx "$DENY" "$RULES"

# Re-sync without --force-gitignore: the ONLY difference is the script-owned
# deny, so the refresh must be recognized as safe and adopted.
env "${SYNC_ENV[@]}" bash "$SYNC" --vault-url "$FIXTURE_VAULT" \
    > "$FIXTURE_ROOT/resync.out" 2>&1 || true

check "the owned built-in deny is adopted despite the empty carve-out config" \
    grep -qFx "$DENY" "$RULES"
refute "no operator-facing overwrite refusal was emitted for a script-owned rule" \
    grep -q "Refusing to overwrite" "$FIXTURE_ROOT/resync.out"

# The behavior the rule exists for: a sub-grace interrupted-stage temp must
# not be stageable into the vault.
printf 'temp bytes\n' > "$FIXTURE_WS/hosts/empty-host/build_log.md.snap.abcdef"
git -C "$FIXTURE_WS" add -A >/dev/null 2>&1 || true
refute "a sub-grace snap temp is NOT staged by git add -A" \
    git -C "$FIXTURE_WS" ls-files --error-unmatch "hosts/empty-host/build_log.md.snap.abcdef"

echo ""
echo "$pass passed, $fail failed"
[ "$fail" -eq 0 ]
