#!/bin/bash
# Persistent Codex CLI implementation of the Sutando core.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../../../.." && pwd)"
cd "$REPO"
# Shared with the claude launcher: one owner for the in-session restart policy.
. "$REPO/src/agent/restart-guard.sh"

TMUX_SOCKET="${SUTANDO_TMUX_SOCKET:-/tmp/sutando-tmux.sock}"
SESSION="${SUTANDO_TMUX_SESSION:-sutando-core}"
WATCHER_SESSION="${SESSION}-watcher"

# --visible (sonichi#2410): open a Terminal window attached to the core after
# boot (or on an already-running no-TTY re-run) via a generated .command +
# `open -a Terminal` — TCC-free, no AppleEvents. Mirrors the claude adapter
# exactly (runtime parity per #2412 review); no-op off macOS / headless.
VISIBLE=0
for _arg in "$@"; do
  [ "$_arg" = "--visible" ] && VISIBLE=1
done

open_visible_terminal() {
  [ "$(uname)" = "Darwin" ] || return 0
  command -v open > /dev/null 2>&1 || return 0
  local ws cmdfile
  ws="$(bash "$REPO/scripts/sutando-config.sh" workspace 2>/dev/null)" || return 0
  [ -n "$ws" ] || return 0
  mkdir -p "$ws/state"
  cmdfile="$ws/state/attach-core.command"
  {
    echo '#!/bin/bash'
    echo '# Auto-generated by start-cli.sh --visible (sonichi#2410) — attaches this'
    echo '# Terminal window to the core session. Safe to re-run; delete freely.'
    echo "exec tmux -S '$TMUX_SOCKET' attach -t '$SESSION'"
  } > "$cmdfile"
  chmod +x "$cmdfile"
  open -a Terminal "$cmdfile" 2>/dev/null || true
}
NOTIFIER_SUPERVISOR="$REPO/src/agent/codex/cli/task-notifier-supervisor.sh"
# Snapshot what we INHERITED before the export below overwrites it: the
# guard must not read the marker this script sets itself.
CALLER_CORE_SESSION="${SUTANDO_CORE_SESSION:-}"
export SUTANDO_CORE_SESSION=1
export SUTANDO_CORE_RUNTIME=codex

# Refuse BEFORE ensure_durable_schedules and the kill-sessions at the
# --restart branch below; both mutate state this caller cannot survive.
if [ "${1:-}" = "--restart" ] && sutando_restart_guard_refuses "$CALLER_CORE_SESSION"; then
  sutando_restart_guard_explain
  exit 1
fi

tmux_available() { command -v tmux >/dev/null 2>&1; }
session_exists() { tmux_available && tmux -S "$TMUX_SOCKET" has-session -t "=$1" 2>/dev/null; }

session_runtime() {
  tmux -S "$TMUX_SOCKET" show-environment -t "=$SESSION" SUTANDO_CORE_RUNTIME 2>/dev/null \
    | sed -n 's/^SUTANDO_CORE_RUNTIME=//p' || true
}

# Codex is installed by the desktop app into ~/.npm-global/bin, which a login
# shell does not necessarily have on PATH: .zprofile is written with the
# bundled git and python3 but not this one. Put the known install dir on PATH
# ourselves rather than trusting what we inherited.
CODEX_INSTALL_BIN="${CODEX_INSTALL_BIN:-$HOME/.npm-global/bin}"
# `codex` is a node script (#!/usr/bin/env node) and a fresh Mac ships no
# system node, so the app's bundled runtime must be reachable or every codex
# invocation dies with "env: node: No such file or directory" (exit 127) —
# which the auth probe below would otherwise misreport as "not authenticated".
# The engine lives at <app-support>/engine; this script runs from
# <app-support>/engine/sutando, so the runtime is one level up from $REPO.
CODEX_NODE_BIN="${CODEX_NODE_BIN:-$(cd "$REPO/.." 2>/dev/null && pwd)/runtime/node/bin}"
# APPEND, never prepend: an operator (or a test harness) who put a codex or
# node earlier on PATH must keep winning; we only add a fallback.
for _d in "$CODEX_NODE_BIN" "$CODEX_INSTALL_BIN"; do
  [ -d "$_d" ] || continue
  case ":$PATH:" in
    *":$_d:"*) ;;
    *) PATH="$PATH:$_d" ;;
  esac
done
export PATH

# The core can be launched while the app is still installing Codex (observed:
# engine unpacked at :25, codex landed at :32 of the following minute). Exiting
# on the first miss leaves a dead window that never recovers even once the
# install finishes, so wait briefly for it to appear before giving up.
CODEX_WAIT_TIMEOUT="${SUTANDO_CODEX_WAIT_TIMEOUT:-120}"
if ! command -v codex >/dev/null 2>&1; then
  echo "  … waiting for the Codex CLI to finish installing (up to ${CODEX_WAIT_TIMEOUT}s)" >&2
  _codex_waited=0
  while [ "$_codex_waited" -lt "$CODEX_WAIT_TIMEOUT" ]; do
    sleep 2
    _codex_waited=$((_codex_waited + 2))
    command -v codex >/dev/null 2>&1 && break
  done
  if command -v codex >/dev/null 2>&1; then
    echo "  ✓ Codex CLI appeared after ${_codex_waited}s" >&2
  else
    echo "Codex CLI is not installed. Install it, run 'codex login', then retry." >&2
    echo "  (looked on PATH and in $CODEX_INSTALL_BIN)" >&2
    exit 127
  fi
fi

# Use the configured CODEX_HOME (or another env name chosen by the operator).
# The default points at ~/.codex to reuse the existing authenticated install.
config_env="$(bash "$REPO/scripts/sutando-config.sh" core-config-dir-env-name codex)"
config_value="$(bash "$REPO/scripts/sutando-config.sh" core-config-dir-value codex)"
if [ -n "$config_env" ] && [ -n "$config_value" ]; then
  mkdir -p "$config_value"
  export "$config_env=$config_value"
  echo "  ✓ $config_env=$config_value"
fi

# `|| _codex_auth_rc=$?` keeps set -e from killing the script on a non-zero
# probe — the exit code IS the signal here, not a failure.
_codex_auth_rc=0
codex login status >/dev/null 2>&1 || _codex_auth_rc=$?
if [ "$_codex_auth_rc" -eq 127 ]; then
  # 127 is "could not execute", not "not logged in" — almost always a missing
  # node on PATH. Saying "run codex login" here sends people the wrong way.
  echo "Codex CLI could not run (exit 127) — its node runtime was not found." >&2
  echo "  PATH lacked a usable node; looked in $CODEX_NODE_BIN" >&2
  exit 127
fi
if [ "$_codex_auth_rc" -ne 0 ]; then
  echo "Codex CLI is not authenticated for ${CODEX_HOME:-~/.codex}. Run 'codex login' and retry." >&2
  exit 1
fi

# The Codex adapter depends on tmux for a persistent pane and fswatch for
# file-bridge wakeups. Match startup.sh's first-run behavior when this launcher
# is invoked directly.
for dependency in tmux fswatch; do
  if ! command -v "$dependency" >/dev/null 2>&1 && command -v brew >/dev/null 2>&1; then
    echo "$dependency not found — installing via Homebrew..."
    brew install "$dependency" 2>&1 | tail -3
  fi
done

WORKING_DIR="${SUTANDO_CODEX_WORKING_DIR:-${SUTANDO_CORE_WORKING_DIR:-$REPO}}"
WORKING_DIR="${WORKING_DIR/#\~/$HOME}"
mkdir -p "$WORKING_DIR"
WORKING_DIR="$(cd "$WORKING_DIR" && pwd -P)"

CORE_ENV_ARGS=(-e SUTANDO_CORE_SESSION=1 -e SUTANDO_CORE_RUNTIME=codex)
[ -n "${SUTANDO_DEFAULT_WORKSPACE:-}" ] && CORE_ENV_ARGS+=(-e "SUTANDO_DEFAULT_WORKSPACE=$SUTANDO_DEFAULT_WORKSPACE")
[ -n "${CODEX_HOME:-}" ] && CORE_ENV_ARGS+=(-e "CODEX_HOME=$CODEX_HOME")
# tmux's server environment can predate the product-mode override, so forward
# the self-development policy explicitly into the persistent core session.
if [ "${SUTANDO_SELF_DEVELOPMENT_ENABLED+x}" = x ]; then
  CORE_ENV_ARGS+=(-e "SUTANDO_SELF_DEVELOPMENT_ENABLED=$SUTANDO_SELF_DEVELOPMENT_ENABLED")
fi

CODEX_ARGS=(
  -C "$WORKING_DIR"
  --add-dir "$HOME"
  --sandbox danger-full-access
  --ask-for-approval never
  --search
  --no-alt-screen
)
if [ -n "${SUTANDO_CORE_MODEL:-}" ]; then
  CODEX_ARGS+=(-m "$SUTANDO_CORE_MODEL")
fi

apply_tmux_defaults() {
  tmux_available || return 0
  tmux -S "$TMUX_SOCKET" start-server 2>/dev/null || true
  tmux -S "$TMUX_SOCKET" set-option -g mouse on 2>/dev/null || true
  tmux -S "$TMUX_SOCKET" bind -n WheelUpPane if-shell -F -t = '#{mouse_any_flag}' 'send-keys -M' 'copy-mode -e; send-keys -M' 2>/dev/null || true
  tmux -S "$TMUX_SOCKET" bind -n WheelDownPane send-keys -M 2>/dev/null || true
}

ensure_task_notifier() {
  local expected_version active_version
  local version_files
  version_files=(
    "$NOTIFIER_SUPERVISOR"
    "$REPO/src/agent/codex/cli/task-notifier.sh"
    "$REPO/src/watch-tasks-stream.sh"
  )
  expected_version="$(
    cksum "${version_files[@]}" \
      | cksum | awk '{print $1 "-" $2}'
  )"
  if session_exists "$WATCHER_SESSION"; then
    active_version="$(
      tmux -S "$TMUX_SOCKET" show-environment -t "=$WATCHER_SESSION" \
        SUTANDO_NOTIFIER_VERSION 2>/dev/null \
        | sed -n 's/^SUTANDO_NOTIFIER_VERSION=//p' || true
    )"
    if [ "$active_version" = "$expected_version" ]; then
      return 0
    fi
    tmux -S "$TMUX_SOCKET" kill-session -t "=$WATCHER_SESSION" 2>/dev/null || true
  fi
  NOTIFIER_ENV_ARGS=(-e "SUTANDO_TMUX_SOCKET=$TMUX_SOCKET" -e "SUTANDO_TMUX_SESSION=$SESSION")
  NOTIFIER_ENV_ARGS+=(-e "SUTANDO_NOTIFIER_VERSION=$expected_version")
  [ -n "${SUTANDO_TASK_EVENT_HANDLER:-}" ] && NOTIFIER_ENV_ARGS+=(-e "SUTANDO_TASK_EVENT_HANDLER=$SUTANDO_TASK_EVENT_HANDLER")
  [ -n "${SUTANDO_ISOLATED_WORKING_DIR:-}" ] && NOTIFIER_ENV_ARGS+=(-e "SUTANDO_ISOLATED_WORKING_DIR=$SUTANDO_ISOLATED_WORKING_DIR")
  [ -n "${CODEX_HOME:-}" ] && NOTIFIER_ENV_ARGS+=(-e "CODEX_HOME=$CODEX_HOME")
  [ -n "${SUTANDO_CORE_MODEL:-}" ] && NOTIFIER_ENV_ARGS+=(-e "SUTANDO_CORE_MODEL=$SUTANDO_CORE_MODEL")
  if [ "${SUTANDO_SELF_DEVELOPMENT_ENABLED+x}" = x ]; then
    NOTIFIER_ENV_ARGS+=(-e "SUTANDO_SELF_DEVELOPMENT_ENABLED=$SUTANDO_SELF_DEVELOPMENT_ENABLED")
  fi
  [ -n "${SUTANDO_TASKS_DIR:-}" ] && NOTIFIER_ENV_ARGS+=(-e "SUTANDO_TASKS_DIR=$SUTANDO_TASKS_DIR")
  [ -n "${SUTANDO_RESULTS_DIR:-}" ] && NOTIFIER_ENV_ARGS+=(-e "SUTANDO_RESULTS_DIR=$SUTANDO_RESULTS_DIR")
  tmux -S "$TMUX_SOCKET" new-session -d -s "$WATCHER_SESSION" \
    "${NOTIFIER_ENV_ARGS[@]}" bash "$NOTIFIER_SUPERVISOR"
}

# Keep the same core-supervisor signal available for both runtimes. The
# monitor's liveness derivation is tmux/session based; its prompt classifier is
# best-effort and safely falls back to the generic running/idle/hung states for
# Codex panes it does not recognize.
ensure_core_monitor() {
  local ws mon_out
  ws="$(bash "$REPO/scripts/sutando-config.sh" workspace 2>/dev/null)" || return 0
  [ -n "$ws" ] || return 0
  mon_out="$ws/state/core-supervisor.json"
  if pgrep -f "core-input-watch\.py .*--socket ${TMUX_SOCKET} .*--out ${mon_out}" >/dev/null 2>&1; then
    return 0
  fi
  python3 "$REPO/src/core-input-watch.py" \
    --socket "$TMUX_SOCKET" --session "$SESSION" --out "$mon_out" \
    >/tmp/core-input-watch.log 2>&1 &
}

# Guarantee this host's core heartbeat writer. src/core_heartbeat.py is the SOLE
# writer of state/cores/<host>.alive; the cron-runner (installed by
# ensure_durable_schedules below) reads that file as its liveness signal —
# local_core_alive() returns False on a missing/stale .alive and cron-runner
# then skips every due launchd fire without advancing the boundary
# (src/cron-runner.py). startup.sh starts the heartbeat, but the Codex launcher
# does not go through startup.sh, so a clean direct start-cli.sh launch would
# migrate schedules and then silently suppress every fire. Start it here (once).
# Guard on the $REPO-anchored path so the check is per-checkout (won't cross-match
# a heartbeat from a different checkout/bundle, and stays hermetic under test).
# One interpreter for the heartbeat, start and stop alike: the repository resolver, never a bare
# `python3` (on a clean macOS host PATH can hand that name to Apple's developer-tools stub).
# Resolved ONCE, in this shell, never inside $(...): a subshell's assignment cannot reach the
# parent, so stop and start would each resolve on their own and could disagree.
_HB_PY=""
resolve_heartbeat_python() {
  [ -r "$REPO/scripts/python-binary.sh" ] || return 0
  # shellcheck source=scripts/python-binary.sh
  . "$REPO/scripts/python-binary.sh"
  _HB_PY="$(resolve_python "$REPO" 2>/dev/null || true)"
}
heartbeat_python() {
  [ -n "$_HB_PY" ] && printf '%s' "$_HB_PY"
}
ensure_core_heartbeat() {
  pgrep -f "$REPO/src/core_heartbeat.py" >/dev/null 2>&1 && return 0
  local _py
  _py="$(heartbeat_python)"
  if [ -z "$_py" ]; then
    echo "WARN no runnable python3 for the core heartbeat — not started; cron-runner fires will stay suppressed" >&2
    return 0
  fi
  "$_py" "$REPO/src/core_heartbeat.py" >/tmp/core-heartbeat.log 2>&1 &
}

ensure_durable_schedules() {
  # Codex has no session CronCreate surface. Reconcile ordinary scheduled
  # prompts onto the existing OS runner before the core session is reused or
  # created, otherwise a runtime switch/restart leaves crons.json populated
  # while every custom schedule silently stops.
  [ "$(uname -s)" = "Darwin" ] || return 0
  local preflight result service
  preflight="$(python3 "$REPO/skills/schedule-crons/scripts/reconcile_launchd.py" --check)" || {
    echo "  ⚠ durable schedule preflight failed" >&2
    return 0
  }
  case "$preflight" in
    *"runner_needed=1"*)
      service="gui/$(id -u)/com.sutando.cron-runner"
      if ! launchctl print "$service" >/dev/null 2>&1; then
        bash "$REPO/src/install-cron-runner-launchd.sh" >/dev/null 2>&1 || {
          echo "  ⚠ durable schedule runner failed to install" >&2
          return 0
        }
        if ! launchctl print "$service" >/dev/null 2>&1; then
          echo "  ⚠ durable schedule runner failed post-install verification" >&2
          return 0
        fi
      fi
      result="$(python3 "$REPO/skills/schedule-crons/scripts/reconcile_launchd.py")" || {
        echo "  ⚠ durable schedule reconciliation failed" >&2
        return 0
      }
      echo "  ✓ durable schedules ($result)"
      ;;
  esac
}

ensure_codex_scheduler() {
  local ws host scheduler
  ws="$(bash "$REPO/scripts/sutando-config.sh" workspace 2>/dev/null)" || return 0
  host="${SUTANDO_HOST_LABEL:-}"
  # Blank-but-set passes `[ -z ]`; trim so it falls through to the resolver.
  host="${host#"${host%%[![:space:]]*}"}"; host="${host%"${host##*[![:space:]]}"}"
  if [ -z "$host" ]; then
    host="$(bash "$REPO/scripts/sutando-config.sh" host-label 2>/dev/null)" || return 0
  fi
  scheduler="${SUTANDO_CODEX_SCHEDULER_SCRIPT:-$REPO/skills/schedule-crons/scripts/codex-scheduler.py}"
  if ! python3 "$scheduler" install --workspace "$ws" --host-label "$host" >/dev/null; then
    echo "  ⚠ Could not reconcile the durable Codex scheduler; run: python3 $scheduler install" >&2
  fi
}

# Codex has no session CronCreate surface. Two complementary reconcilers run on
# every launcher invocation, partitioned by reconcile_launchd.py's eligibility
# rules so no entry is double-owned: ensure_durable_schedules moves ordinary
# fixed crons.json entries onto the OS-backed cron-runner (skipping main-loop,
# codex-task entries, and anything already launchd-owned), and
# ensure_codex_scheduler owns execution:codex-task entries plus the canonical
# five-minute main loop while this runtime is selected.
ensure_durable_schedules
ensure_codex_scheduler
resolve_heartbeat_python

if [ "${1:-}" = "--restart" ]; then
  tmux_available && tmux -S "$TMUX_SOCKET" kill-session -t "=$WATCHER_SESSION" 2>/dev/null || true
  tmux_available && tmux -S "$TMUX_SOCKET" kill-session -t "=$SESSION" 2>/dev/null || true
  # Hand the heartbeat over as well: ensure_core_heartbeat only starts one when none is running.
  _hb_py="$(heartbeat_python)"
  if [ -n "$_hb_py" ]; then
    "$_hb_py" "$REPO/src/core_heartbeat.py" --stop >/dev/null 2>&1 || echo "WARN heartbeat handoff (--stop) failed — old writer may still be running" >&2
  else
    echo "WARN no runnable python3 for the heartbeat handoff — old writer left running" >&2
  fi
elif session_exists "$SESSION" && [ "$(session_runtime)" != "codex" ]; then
  # Sessions created before runtime markers existed are Claude sessions. Never
  # attach a selected Codex launcher to an unknown/foreign canonical session.
  echo "Replacing unmarked or non-Codex $SESSION session."
  tmux -S "$TMUX_SOCKET" kill-session -t "=$WATCHER_SESSION" 2>/dev/null || true
  tmux -S "$TMUX_SOCKET" kill-session -t "=$SESSION" 2>/dev/null || true
fi

if session_exists "$SESSION"; then
  apply_tmux_defaults
  ensure_task_notifier
  ensure_core_monitor
  ensure_core_heartbeat
  if [ -t 1 ] && [ -z "${TMUX:-}" ]; then
    echo "Attaching to existing $SESSION (Ctrl-b d to detach)..."
    exec tmux -S "$TMUX_SOCKET" attach -t "$SESSION"
  fi
  if [ "$VISIBLE" = 1 ]; then
    open_visible_terminal
    echo "$SESSION already running (codex) — opened a Terminal window attached to it."
    exit 0
  fi
  echo "$SESSION already running (codex)."
  exit 0
fi

# Past the attach/reuse exit above, so this is a genuine Codex core boot. The
# sentinel is cleared at each launch site below, never before one can fail.
if [ -r "$REPO/scripts/python-binary.sh" ]; then
  # The one interpreter resolved above serves the policy read too: one resolution per launch.
  _sd_py="$_HB_PY"
else
  _sd_py=""
fi
clear_shutdown_sentinel() {
  if [ -n "$_sd_py" ]; then
    "$_sd_py" "$REPO/src/shutdown.py" clear >/dev/null \
      || echo "start-cli.sh: shutdown.py clear failed — the intake gate may hold tasks" >&2
  else
    echo "start-cli.sh: no runnable interpreter — shutdown sentinel NOT cleared" >&2
  fi
}
# Clearing the sentinel before a launch that never yields a live core opens
# intake with nothing serving, so exec paths stash it and restore on failure.
_SENTINEL_STASH=""
# Without execfail bash exits 127 on a failed exec, which would make every
# restore-after-exec below unreachable dead code.
shopt -s execfail
stash_shutdown_sentinel() {
  _SENTINEL_STASH=""
  [ -n "$_sd_py" ] || return 0
  _sp="$("$_sd_py" "$REPO/src/shutdown.py" path 2>/dev/null)" || return 0
  [ -n "$_sp" ] && [ -f "$_sp" ] || return 0
  _SENTINEL_STASH="$(mktemp "${TMPDIR:-/tmp}/sutando-sentinel.XXXXXX" 2>/dev/null)" || return 0
  cp "$_sp" "$_SENTINEL_STASH" 2>/dev/null || _SENTINEL_STASH=""
}
# Only reachable when exec FAILED: exec never returns on success.
restore_shutdown_sentinel() {
  [ -n "$_SENTINEL_STASH" ] && [ -f "$_SENTINEL_STASH" ] || return 0
  _sp="$("$_sd_py" "$REPO/src/shutdown.py" path 2>/dev/null)" || return 0
  if [ -n "$_sp" ]; then
    mkdir -p "$(dirname "$_sp")" 2>/dev/null || true
    cp "$_SENTINEL_STASH" "$_sp" 2>/dev/null \
      || echo "start-cli.sh: could not restore the shutdown sentinel after a failed launch" >&2
  fi
  rm -f "$_SENTINEL_STASH" 2>/dev/null || true
  _SENTINEL_STASH=""
}

if ! tmux_available; then
  echo "  ⚠ tmux not found — Codex will run, but file-bridge task wakeups are unavailable" >&2
  if ! command -v codex >/dev/null 2>&1; then
    echo "  ⚠ codex not found — not clearing the shutdown sentinel, no core can start." >&2
    exit 127
  fi
  stash_shutdown_sentinel
  clear_shutdown_sentinel
  # errexit would exit on the failed exec before the restore below is reached;
  # drop it just around the exec and re-raise the exec's own status.
  set +e
  exec codex "${CODEX_ARGS[@]}"
  _exec_rc=$?
  set -e
  restore_shutdown_sentinel
  echo "  ⚠ codex failed to exec — shutdown sentinel restored, no core is live." >&2
  exit "$_exec_rc"
fi

if ! command -v fswatch >/dev/null 2>&1; then
  echo "fswatch not found — install it to enable Sutando task wakeups (brew install fswatch)." >&2
  exit 127
fi

apply_tmux_defaults

publish_active_runtime() {
  # Only callers that have VERIFIED the session may call this: a launch that
  # never came up must leave the previous runtime's marker truthful.
  local ws
  ws="$(bash "$REPO/scripts/sutando-config.sh" workspace 2>/dev/null)" || return 0
  [ -n "$ws" ] || return 0
  mkdir -p "$ws/state" 2>/dev/null || true
  printf '{"runtime":"codex","session":"%s","started_at":%s}\n' \
    "$SESSION" "$(date +%s)" > "$ws/state/core-runtime.json" 2>/dev/null || true
}

# Append-only launch history, not a claim about what is live, so it is
# unconditional — unlike the active-runtime marker above.
if ws="$(bash "$REPO/scripts/sutando-config.sh" workspace 2>/dev/null)" && [ -n "$ws" ]; then
  mkdir -p "$ws/state"
  printf '{"host":"%s","session_started_at":%s,"iso":"%s","source":"start-cli","runtime":"codex"}\n' \
    "$(hostname | sed 's/\..*//')" "$(date +%s)" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    >> "$ws/state/session-starts.log"
fi

if [ -t 1 ] && [ -z "${TMUX:-}" ]; then
  tmux -S "$TMUX_SOCKET" new-session -d -s "$SESSION" "${CORE_ENV_ARGS[@]}" codex "${CODEX_ARGS[@]}"
  # new-session rc=0 means tmux accepted it; a child that exits at once leaves
  # has-session failing. Poll before opening intake rather than assuming.
  for _ in $(seq 1 25); do
    session_exists "$SESSION" && break
    sleep 0.2
  done
  if session_exists "$SESSION"; then
    clear_shutdown_sentinel
    publish_active_runtime
  else
    echo "  ⚠ $SESSION did not come up within ~5s — sentinel NOT cleared, no core is serving." >&2
  fi
  ensure_task_notifier
  ensure_core_monitor
  ensure_core_heartbeat
  exec tmux -S "$TMUX_SOCKET" attach -t "$SESSION"
else
  tmux -S "$TMUX_SOCKET" new-session -d -s "$SESSION" "${CORE_ENV_ARGS[@]}" codex "${CODEX_ARGS[@]}"
  # new-session rc=0 means tmux accepted it; a child that exits at once leaves
  # has-session failing. Poll before opening intake rather than assuming.
  for _ in $(seq 1 25); do
    session_exists "$SESSION" && break
    sleep 0.2
  done
  if session_exists "$SESSION"; then
    clear_shutdown_sentinel
    publish_active_runtime
  else
    echo "  ⚠ $SESSION did not come up within ~5s — sentinel NOT cleared, no core is serving." >&2
  fi
  ensure_task_notifier
  ensure_core_monitor
  ensure_core_heartbeat
  if [ "$VISIBLE" = 1 ]; then
    open_visible_terminal
    echo "Started $SESSION detached with Codex — opened a Terminal window attached to it."
  else
    echo "Started $SESSION detached with Codex. Attach via:"
    echo "  tmux -S $TMUX_SOCKET attach -t $SESSION"
  fi
fi
