#!/usr/bin/env python3
"""Generate src/header_keys.ts from local_task_protocol.KNOWN_HEADER_KEYS.

The TS guards defang forged header lines and must cover exactly the keys the
Python reader accepts. Three hand-maintained copies drifted key by key; this
makes the TS side an ARTIFACT of the Python owner instead of a second source.
"""
from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OWNER = REPO / "src" / "local_task_protocol.py"
OUT = REPO / "src" / "header_keys.ts"


def keys() -> tuple:
    spec = importlib.util.spec_from_file_location("_ltp_gen", OWNER)
    mod = importlib.util.module_from_spec(spec)
    # @dataclass resolves sys.modules[cls.__module__]; an unregistered module
    # makes that None and the import dies inside dataclasses, not here.
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return tuple(mod.KNOWN_HEADER_KEYS)


def render(ks: tuple) -> str:
    body = "\n".join(f"\t'{k}'," for k in ks)
    return (
        "// GENERATED by scripts/gen-header-keys.py — do not edit.\n"
        "// Source of truth: src/local_task_protocol.py KNOWN_HEADER_KEYS.\n"
        "// Regenerate after adding a key; tests/header-keys-generated.test.py\n"
        "// fails if this file is stale.\n"
        "export const HEADER_KEYS: readonly string[] = [\n"
        f"{body}\n"
        "];\n"
        "\n"
        "/** Alternation source for a header-line guard. Keys are plain\n"
        " *  identifiers, so no escaping is needed and none is invented here. */\n"
        "export const HEADER_KEY_ALTERNATION: string = HEADER_KEYS.join('|');\n"
    )


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = render(keys())
    if "--check" in argv:
        current = OUT.read_text() if OUT.is_file() else ""
        if current == text:
            print(f"gen-header-keys: {OUT.relative_to(REPO)} is current")
            return 0
        print(f"gen-header-keys: STALE — {OUT.relative_to(REPO)} does not match "
              f"{OWNER.relative_to(REPO)}. Run: python3 scripts/gen-header-keys.py",
              file=sys.stderr)
        return 1
    OUT.write_text(text)
    print(f"gen-header-keys: wrote {OUT.relative_to(REPO)} ({len(keys())} keys)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
