#!/usr/bin/env python3
"""Generate docs/src-map.md — a one-line-per-module index of src/.

WHY THIS EXISTS
    An agent working on this repo (Claude Code or Codex, per `core.runtime`)
    has CLAUDE.md / AGENTS.md for the operating protocol, but nothing that maps
    the code. src/ is ~160 files; the only orientation is CLAUDE.md's four-entry
    "Workspace layout" and README's user-facing capability table. Finding where
    something lives means grepping, and grepping a 38k-line tree burns the
    context budget CLAUDE.md is otherwise careful to protect.

    The raw material already exists: every top-level src/ file opens with a
    substantive header comment. This script indexes what is already written
    rather than inventing new prose, so the map cannot drift from the code's own
    description of itself — and a stale entry is a signal the header is stale.

DESIGN
    - PURPOSE LINE ONLY, no symbol dumps. `grep` and LSP already answer "where is
      symbol X". Neither answers "what is this file for", which is the actual gap.
      Keeping it to one line also keeps the artifact small enough to read.
    - Generated + `--check`ed in CI, mirroring scripts/agents-md-sync.sh. A map
      nobody regenerates is worse than no map, because it is confidently wrong.
    - Deterministic output (sorted, no timestamps) so --check never false-fires.

USAGE
    python3 scripts/gen-src-map.py            # regenerate docs/src-map.md
    python3 scripts/gen-src-map.py --check    # exit 1 if stale
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
OUT = REPO / "docs" / "src-map.md"

SUFFIXES = (".ts", ".py", ".sh", ".mjs")

# Directories under src/ that are not agent-facing source.
SKIP_DIRS = {"node_modules", "__pycache__", ".git", "dist", "build"}

# Lines that open a file but carry no meaning for a reader.
_NOISE = re.compile(
    r"^(#!|/\*+$|\*+/$|\"\"\"$|'''$|//\s*$|#\s*$|\*\s*$|-{3,}$|={3,}$)"
)
# Comment/docstring markers to strip from the front of a line.
_LEAD = re.compile(r"^(\s*(?:/\*\*?|\*/?|//+|#+|\"\"\"|''')\s?)")


def purpose(path: Path) -> str:
    """First meaningful line of the file's header comment.

    Reads only the top of the file — the header is by definition at the top, and
    scanning whole files would make this slow for no benefit.
    """
    try:
        head = path.read_text(encoding="utf-8", errors="replace").split("\n")[:25]
    except OSError:
        return ""
    for raw in head:
        line = raw.strip()
        if not line or _NOISE.match(line):
            continue
        stripped = _LEAD.sub("", line).strip()
        # Skip shebangs, coding cookies, and lines that are pure punctuation.
        if not stripped or stripped.startswith(("!", "-*-")):
            continue
        # `from __future__ import ...` is required to precede everything else, so
        # several modules put it ABOVE their docstring (src/vault_intercept.py,
        # src/screen-capture-server.py). Treat it as boilerplate and keep looking
        # — bailing here reported those two as undocumented when they are not.
        if stripped.startswith("from __future__ import"):
            continue
        # Any other line of code means the file has no header comment — say so
        # plainly rather than quoting an import statement as if it were a purpose.
        if re.match(r"^(import|from|const|let|var|export|set |function|def |class |source |\.)", stripped):
            return ""
        return stripped.rstrip()
    return ""


def collect() -> list[tuple[str, str]]:
    rows = []
    for p in sorted(SRC.rglob("*")):
        if not p.is_file() or p.suffix not in SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in p.relative_to(REPO).parts):
            continue
        # Test files describe a test, not a module of the system.
        if ".test." in p.name:
            continue
        rows.append((str(p.relative_to(REPO)), purpose(p)))
    return rows


def render(rows: list[tuple[str, str]]) -> str:
    undocumented = [r for r, d in rows if not d]
    out = [
        "<!-- GENERATED by scripts/gen-src-map.py — do not edit by hand. -->",
        "<!-- Edit the module's own header comment, then re-run the script.  -->",
        "",
        "# src/ module map",
        "",
        "One line per module, taken from that file's own header comment. This is a",
        "lookup, not required reading — it is deliberately NOT loaded into every",
        "session (see CLAUDE.md's note on context budget).",
        "",
        "If an entry reads wrong, the file's header comment is wrong: fix the header",
        "and re-run `python3 scripts/gen-src-map.py`.",
        "",
        f"{len(rows)} modules indexed"
        + (f", {len(undocumented)} without a usable header comment." if undocumented else "."),
        "",
    ]

    # Group by directory so related modules read together.
    groups: dict[str, list[tuple[str, str]]] = {}
    for rel, desc in rows:
        groups.setdefault(str(Path(rel).parent), []).append((rel, desc))

    for group in sorted(groups):
        out.append(f"## `{group}/`")
        out.append("")
        for rel, desc in groups[group]:
            name = Path(rel).name
            out.append(f"- **`{name}`** — {desc}" if desc else f"- **`{name}`** — _(no header comment)_")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    rendered = render(collect())
    check = "--check" in sys.argv[1:]

    if check:
        if not OUT.exists():
            print(f"gen-src-map: {OUT.relative_to(REPO)} is missing — run 'python3 scripts/gen-src-map.py'", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") == rendered:
            print("gen-src-map: docs/src-map.md is up to date")
            return 0
        print(
            "gen-src-map: docs/src-map.md is stale — run 'python3 scripts/gen-src-map.py' and commit the result",
            file=sys.stderr,
        )
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"gen-src-map: wrote {OUT.relative_to(REPO)} ({len(collect())} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
