#!/usr/bin/env bash
# Generate PR before/after evidence by RUNNING the commands and capturing their
# real output, so the author never transcribes and therefore cannot invent it.
#
# Usage:
#   bash scripts/pr-evidence.sh 'cmd' ['cmd' ...]           # run at the current HEAD
#   bash scripts/pr-evidence.sh --at <ref> 'cmd' ['cmd' ...] # run at <ref>, workspace-pinned
#
# Prints a markdown block: each command, its verbatim stdout+stderr, its exit
# code, and a stamp naming the sha the block was produced at. Paste it whole.
#
# --at builds the "before" half without touching the live checkout, and pins the
# temporary worktree at the LIVE workspace. CONTRIBUTING warns why: an unpinned
# worktree resolves its own empty workspace/ and every workspace-reading probe
# reports clean no matter what the code does — false-clean evidence.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REF=""
WT=""
WTPARENT=""

usage() { sed -n '2,12p' "$0"; exit "${1:-0}"; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        --at) REF="${2:?--at needs a ref}"; shift 2;;
        -h|--help) usage 0;;
        --) shift; break;;
        -*) echo "pr-evidence: unknown flag '$1'" >&2; usage 2;;
        *) break;;
    esac
done
[[ $# -gt 0 ]] || { echo "pr-evidence: no commands given" >&2; usage 2; }

# Failures are reported, not swallowed: a stranded worktree holds a pinned
# config, and silence is how it stays on disk unnoticed.
cleanup() {
    if [[ -n "$WT" && -d "$WT" ]]; then
        git -C "$REPO" worktree remove --force "$WT" >/dev/null 2>&1 \
            || echo "pr-evidence: WARNING — could not remove worktree $WT" >&2
    fi
    if [[ -n "$WTPARENT" && -d "$WTPARENT" ]]; then
        rm -rf "$WTPARENT" \
            || echo "pr-evidence: WARNING — left $WTPARENT on disk" >&2
    fi
    return 0
}
trap cleanup EXIT

RUNDIR="$REPO"
if [[ -n "$REF" ]]; then
    git -C "$REPO" rev-parse --verify --quiet "$REF^{commit}" >/dev/null \
        || { echo "pr-evidence: '$REF' is not a commit in this repo" >&2; exit 2; }

    # Resolve BEFORE the worktree exists, and unconditionally — not only when a
    # local config file happens to be present. An unpinned worktree resolves its
    # own empty workspace/ and reports clean whatever the code does.
    LIVE_WS="$(bash "$REPO/scripts/sutando-config.sh" workspace 2>/dev/null || true)"
    [[ -n "$LIVE_WS" ]] || {
        echo "pr-evidence: cannot resolve the live workspace — refusing --at rather than" >&2
        echo "pr-evidence: emitting evidence from an empty one." >&2
        exit 2
    }

    # mktemp gives 0700; `git worktree add` makes its own dir 0755, so the
    # worktree goes INSIDE the private parent rather than being it.
    WTPARENT="$(mktemp -d "${TMPDIR:-/tmp}/pr-evidence-XXXXXX")"
    WT="$WTPARENT/wt"
    git -C "$REPO" worktree add --detach --quiet "$WT" "$REF" \
        || { echo "pr-evidence: could not create a worktree at '$REF'" >&2; exit 2; }
    RUNDIR="$WT"

    # Write a MINIMAL config — never copy the real one. It carries unrelated
    # local settings (vault, migrate) that this tool has no need to duplicate.
    ( umask 077
      python3 - "$WT/sutando.config.local.json" "$LIVE_WS" <<'PY'
import json, pathlib, sys
pathlib.Path(sys.argv[1]).write_text(
    json.dumps({"workspace": {"path": sys.argv[2]}}, indent=2) + "\n")
PY
    ) || { echo "pr-evidence: could not pin the worktree's workspace" >&2; exit 2; }
    chmod 600 "$WT/sutando.config.local.json"
    echo "pr-evidence: worktree at $REF pinned to workspace $LIVE_WS" >&2
fi

SHA="$(git -C "$RUNDIR" rev-parse HEAD)"
LABEL="${REF:-HEAD}"

printf '<!-- pr-evidence %s %s -->\n' "$LABEL" "$SHA"
# shellcheck disable=SC2016  # the backticks are markdown, not command substitution
printf '**Evidence at `%s` (`%s`)** — generated by `scripts/pr-evidence.sh`, not transcribed.\n\n' \
    "$LABEL" "${SHA:0:8}"
printf '```\n'
for cmd in "$@"; do
    printf '$ %s\n' "$cmd"
    out="$(cd "$RUNDIR" && eval "$cmd" 2>&1)"
    rc=$?
    [[ -n "$out" ]] && printf '%s\n' "$out"
    printf '[exit %d]\n\n' "$rc"
done
printf '```\n'
