#!/usr/bin/env python3
"""Generate (or --check) the consumer copies of the credential contract.

One source, two generated artifacts (owner ruling 2026-08-05):

    shared/ag2_gateway_credentials.py                       CANONICAL
      -> packages/ag2-sparrow/ag2_sparrow/gateway_credentials.py
      -> skills/agent-room-ops/gateway_credentials.py

--check regenerates IN MEMORY and byte-compares against the repo copies —
comparing each copy to freshly-generated output (not copies to each other,
which would miss both drifting together). Any difference exits 1 for CI.

Usage:  python3 tools/sync_gateway_credentials.py          # (re)write copies
        python3 tools/sync_gateway_credentials.py --check  # CI guard
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Repo root via git (the sanctioned way — the workspace-resolution lint
# rejects __file__ parent-walks outside exempted paths). This tool only ever
# runs from a checkout (CI + developers), where git is guaranteed.
REPO = Path(subprocess.run(["git", "rev-parse", "--show-toplevel"],
                           capture_output=True, text=True, check=True,
                           cwd=Path(__file__).parent).stdout.strip())
CANONICAL = REPO / "shared" / "ag2_gateway_credentials.py"
HEADER = ("# GENERATED FROM shared/ag2_gateway_credentials.py.\n"
          "# DO NOT EDIT THIS FILE DIRECTLY — edit the canonical source and\n"
          "# run: python3 tools/sync_gateway_credentials.py\n")
TARGETS = (
    REPO / "packages" / "ag2-sparrow" / "ag2_sparrow" / "gateway_credentials.py",
    REPO / "skills" / "agent-room-ops" / "gateway_credentials.py",
)


def generated_content() -> str:
    return HEADER + CANONICAL.read_text()


def main() -> int:
    want = generated_content()
    if "--check" in sys.argv:
        bad = [str(t.relative_to(REPO)) for t in TARGETS
               if not t.exists() or t.read_text() != want]
        if bad:
            print("credential-contract drift — regenerate with "
                  "tools/sync_gateway_credentials.py:\n  " + "\n  ".join(bad))
            return 1
        print(f"ok: {len(TARGETS)} generated copies match canonical")
        return 0
    for t in TARGETS:
        t.write_text(want)
        print(f"wrote {t.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
