#!/usr/bin/env python3
"""Trusted image generation for Signal Room tasks — the enforced half of the output contract.

The task body tells the worker WHERE a generated image may go; this wrapper is the
only path that can put one there. The worker supplies a prompt (plus an optional
size preset) and a bare output filename. The output root comes ONLY from
SIGNAL_TASK_OUTPUT_ROOT, which `signal_worker_launch.py` derives server-side from
the task id when it launches the worker. Nothing on the command line can name a
path: the root must be a plain (non-symlink) `<results>/<task-signal-*>` directory
opened by descriptor, the name carries no separators and a fixed `.png`, and the
file is created O_CREAT|O_EXCL|O_NOFOLLOW relative to that descriptor.

    SIGNAL_TASK_OUTPUT_ROOT=<results>/<task_id> \\
        python3 src/signal_image_gen.py --prompt "..." --name chart.png [--size square|landscape|portrait]

Prints the absolute path of the written file — the worker announces it as
`[file: <path>]`. Exit 2 = refused input or root, 1 = the provider produced no image.
"""

from __future__ import annotations

import argparse
import importlib.util
import io
import os
import re
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from signal_room_tasks import SIGNAL_TASK_PREFIX  # noqa: E402
from workspace_default import resolve_workspace  # noqa: E402

OUTPUT_ROOT_ENV = "SIGNAL_TASK_OUTPUT_ROOT"
SIZE_PRESETS = {"square": "1:1", "landscape": "16:9", "portrait": "9:16"}
OUTPUT_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{0,63}\.png\Z")
TASK_ID_RE = re.compile(r"^[A-Za-z0-9_\-.]+\Z")
PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
MAX_PROMPT_CHARS = 4000
DEFAULT_MODEL = "gemini-3.1-flash-image-preview"
SKILL_SCRIPT = Path(__file__).resolve().parent.parent / "skills" / "image-generation" / "scripts" / "generate.py"


class GenerationRefused(Exception):
    """Input or output root outside the contract; nothing was written."""


def valid_output_name(name) -> bool:
    return isinstance(name, str) and bool(OUTPUT_NAME_RE.match(name))


def open_output_root(root, results_dir) -> int:
    """Descriptor for `root`, which must be `<canonical results dir>/<task-signal-*>`,
    reached by two O_NOFOLLOW opens (the results dir, then the task dir under it)."""
    if not isinstance(root, str) or not os.path.isabs(root) or os.path.normpath(root) != root:
        raise GenerationRefused("output root must be an absolute, normalized path")
    base, task_id = os.path.split(root)
    if base != os.path.realpath(str(results_dir)):
        raise GenerationRefused("output root is not directly under the results dir")
    if not task_id.startswith(SIGNAL_TASK_PREFIX) or not TASK_ID_RE.match(task_id):
        raise GenerationRefused("output root is not a Signal Room task dir")
    try:
        base_fd = os.open(base, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    except OSError:
        raise GenerationRefused("results dir is not a plain directory")
    try:
        fd = os.open(task_id, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW, dir_fd=base_fd)
    except OSError:
        raise GenerationRefused("task output dir is not a plain directory")
    finally:
        os.close(base_fd)
    if not stat.S_ISDIR(os.fstat(fd).st_mode):
        os.close(fd)
        raise GenerationRefused("task output dir is not a plain directory")
    return fd


def to_png(data: bytes) -> bytes:
    if data.startswith(PNG_MAGIC):
        return data
    try:
        from PIL import Image
    except ImportError:
        raise RuntimeError("provider returned a non-PNG image and Pillow is not installed")
    buf = io.BytesIO()
    Image.open(io.BytesIO(data)).save(buf, "PNG")
    return buf.getvalue()


def write_output(root_fd: int, name: str, data: bytes) -> None:
    """Create `name` under the root descriptor: new file only, never through a link."""
    if not valid_output_name(name):
        raise GenerationRefused("output name must be a bare <name>.png with no separators")
    if not data.startswith(PNG_MAGIC):
        raise GenerationRefused("generated bytes are not a PNG image")
    try:
        fd = os.open(name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600, dir_fd=root_fd)
    except FileExistsError:
        raise GenerationRefused("output name already exists")
    with os.fdopen(fd, "wb") as fh:
        fh.write(data)
        fh.flush()
        os.fsync(fh.fileno())


def gemini_provider(prompt: str, aspect: str | None) -> bytes:
    """The image-generation skill's own Gemini path, returning bytes instead of a file."""
    if not SKILL_SCRIPT.is_file():
        raise RuntimeError("image-generation skill is not installed")
    spec = importlib.util.spec_from_file_location("image_generation_skill", SKILL_SCRIPT)
    skill = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(skill)
    skill.load_env()
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY not set")
    from google import genai
    from google.genai import types
    config = {"response_modalities": ["IMAGE", "TEXT"]}
    if aspect and hasattr(types, "ImageConfig"):
        config["image_config"] = types.ImageConfig(aspect_ratio=aspect)
    response = genai.Client(api_key=api_key).models.generate_content(
        model=os.environ.get("IMAGE_MODEL", DEFAULT_MODEL), contents=[prompt],
        config=types.GenerateContentConfig(**config))
    for candidate in response.candidates or []:
        for part in candidate.content.parts:
            if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                return part.inline_data.data
    raise RuntimeError("no image in response")


def run(argv, env, provider, results_dir, out=sys.stdout, err=sys.stderr) -> int:
    parser = argparse.ArgumentParser(prog="signal_image_gen", add_help=True)
    parser.add_argument("--prompt", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--size", choices=sorted(SIZE_PRESETS), default=None)
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        return 2 if exc.code else 0
    try:
        prompt = args.prompt.strip()
        if not prompt or len(prompt) > MAX_PROMPT_CHARS:
            raise GenerationRefused(f"prompt must be 1..{MAX_PROMPT_CHARS} characters")
        if not valid_output_name(args.name):
            raise GenerationRefused("output name must be a bare <name>.png with no separators")
        root = env.get(OUTPUT_ROOT_ENV)
        if not root:
            raise GenerationRefused(f"{OUTPUT_ROOT_ENV} is not set; run under signal_worker_launch.py")
        root_fd = open_output_root(root, results_dir)
    except GenerationRefused as exc:
        print(f"signal_image_gen: refused: {exc}", file=err)
        return 2
    try:
        try:
            data = to_png(provider(prompt, SIZE_PRESETS.get(args.size)))
        except Exception as exc:  # noqa: BLE001 — any provider failure is "no image"
            print(f"signal_image_gen: no image: {exc}", file=err)
            return 1
        try:
            write_output(root_fd, args.name, data)
        except GenerationRefused as exc:
            print(f"signal_image_gen: refused: {exc}", file=err)
            return 2
    finally:
        os.close(root_fd)
    print(os.path.join(root, args.name), file=out)
    return 0


def main() -> int:
    return run(sys.argv[1:], os.environ, gemini_provider, resolve_workspace() / "results")


if __name__ == "__main__":
    sys.exit(main())
