"""Steady-state retention for Signal Room task-output dirs (R3).

`src/archive-stale-results.py` runs once at startup, so a long-lived host would
never reclaim `<results>/<task_id>/` dirs the generated-image capability creates.
agent-api therefore runs an hourly in-process sweep: it re-runs the startup
archiver's own `main()` for stale result texts, then ages out task-output dirs.

Liveness is a lease file (`<results>/<task_id>/.lease`) that every `/file-bytes`
serve touches. A dir is removed only once its lease — or, when no serve ever
happened, its newest mtime — is older than LEASE_STALE_SEC (26 h): strictly past
the daemon job's 24 h retry horizon plus its longest backoff, so generated bytes
survive every legitimate re-serve without job-side renewal. A lockfile keeps two
sweeps (threads or processes) from racing.

Serve vs. sweep is a per-task flock on `<state>/task-leases/<task_id>.lock`: a
serve holds it SHARED for its whole open/reserve/touch/stream, the sweeper takes
it EXCLUSIVE (non-blocking — a busy task is skipped), re-reads the lease under
it and deletes while holding it. The flock files — this one and the serve-quota
`.lock` — are NEVER unlinked: unlinking a held lock file lets the next opener
create a second inode, and two holders stop excluding each other. The sweeper
removes the task dir, confirms deletion by ENOENT on a fresh stat, and only then
removes the serve-quota counter agent-api keeps in `<state>/serve-quota/`; an
rmtree failure is logged and the dir simply waits for the next pass.

The counter itself is written as a durable zero at publish (`init_serve_quota`),
before the task dir exists — so a serve that finds no counter for a task that
exists is looking at corruption and refuses, not at a fresh task.
"""

from __future__ import annotations

import fcntl
import json
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from signal_room_tasks import SIGNAL_TASK_PREFIX  # noqa: E402

LEASE_NAME = ".lease"
LEASE_STALE_SEC = 26 * 3600
SWEEP_INTERVAL_SEC = 3600
LOCK_NAME = ".task-output-sweep.lock"
LOCK_STALE_SEC = 3600
LEASE_LOCK_DIRNAME = "task-leases"
SERVE_QUOTA_DIRNAME = "serve-quota"


def touch_lease(task_dir, now: float | None = None) -> None:
    """Mark `task_dir` live; called by the serving path on every authorized serve."""
    lease = Path(task_dir) / LEASE_NAME
    # The dir is task-writable: never follow a planted `.lease` link anywhere.
    fd = os.open(lease, os.O_WRONLY | os.O_CREAT | os.O_NOFOLLOW, 0o600)
    try:
        stamp = time.time() if now is None else now
        os.utime(fd, (stamp, stamp))
    finally:
        os.close(fd)


def _state_file(state_dir, dirname: str, name: str) -> Path:
    directory = Path(state_dir) / dirname
    directory.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(directory, 0o700)
    return directory / name


def lease_lock_path(state_dir, task_id: str) -> Path:
    return _state_file(state_dir, LEASE_LOCK_DIRNAME, f"{task_id}.lock")


def serve_quota_paths(state_dir, task_id: str) -> tuple[Path, Path]:
    """(counters, lock) for agent-api's per-task serve envelope."""
    return (_state_file(state_dir, SERVE_QUOTA_DIRNAME, f"{task_id}.json"),
            _state_file(state_dir, SERVE_QUOTA_DIRNAME, f"{task_id}.lock"))


def _fsync_dir(directory) -> None:
    fd = os.open(directory, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


def write_serve_quota(quota, payload: dict) -> None:
    """Atomic 0600 replace of the counter (temp + fsync + rename), then fsync of its dir."""
    quota = Path(quota)
    fd, tmp = tempfile.mkstemp(dir=str(quota.parent), prefix=f".{quota.stem}.", suffix=".tmp")
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(payload, fh)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp, quota)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    _fsync_dir(quota.parent)


def init_serve_quota(state_dir, task_id: str) -> Path:
    """The durable zero counter, written at publish BEFORE the task dir exists; never resets one."""
    quota, _lock = serve_quota_paths(state_dir, task_id)
    if not quota.exists():
        write_serve_quota(quota, {"v": 1, "files": [], "serves": 0, "bytes": 0})
    return quota


def _open_lease_lock(state_dir, task_id: str) -> int:
    return os.open(lease_lock_path(state_dir, task_id), os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW, 0o600)


def hold_task_lease(state_dir, task_id: str) -> int:
    """SHARED flock a serve holds from open to last byte; the caller closes the fd."""
    fd = _open_lease_lock(state_dir, task_id)
    try:
        fcntl.flock(fd, fcntl.LOCK_SH)
    except BaseException:
        os.close(fd)
        raise
    return fd


def _remove_serve_quota(state_dir, task_id: str) -> None:
    """The counter goes with the dir; the flock files beside it stay (stable inodes)."""
    try:
        os.unlink(serve_quota_paths(state_dir, task_id)[0])
    except OSError:
        pass


def _gone(path) -> bool:
    """Deletion is confirmed only by ENOENT on a fresh stat; any other answer is 'still there'."""
    try:
        os.lstat(path)
    except FileNotFoundError:
        return True
    except OSError:
        return False
    return False


def _lease_mtime(task_dir: Path) -> float | None:
    try:
        return os.lstat(task_dir / LEASE_NAME).st_mtime
    except OSError:
        return None


def _liveness(task_dir: Path) -> float:
    """Lease mtime when one exists; otherwise the newest mtime in the dir."""
    lease = _lease_mtime(task_dir)
    if lease is not None:
        return lease
    newest = os.lstat(task_dir).st_mtime
    try:
        with os.scandir(task_dir) as entries:
            for entry in entries:
                try:
                    newest = max(newest, entry.stat(follow_symlinks=False).st_mtime)
                except OSError:
                    continue
    except OSError:
        pass
    return newest


def _acquire_lock(results_dir: Path, now: float) -> bool:
    lock = results_dir / LOCK_NAME
    for _attempt in (1, 2):
        try:
            fd = os.open(lock, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            try:
                if now - os.stat(lock).st_mtime <= LOCK_STALE_SEC:
                    return False
                os.unlink(lock)
            except OSError:
                return False
            continue
        with os.fdopen(fd, "w") as fh:
            fh.write(str(os.getpid()))
        return True
    return False


def sweep_task_outputs(results_dir, now: float | None = None, *, state_dir=None) -> dict:
    """One pass: remove abandoned `task-signal-*` dirs, keep live ones.

    Returns {"removed": [...], "kept": [...], "busy": [...], "failed": [...],
    "skipped": reason|None} with dir names, so a caller (or test) can see exactly
    what happened. `busy` lists dirs a serve held at that moment; `failed` lists
    dirs whose removal did not complete — their state is untouched and they are
    retried next pass. `state_dir` defaults to the workspace `state/` beside the
    results dir.
    """
    results_dir = Path(results_dir)
    state_dir = results_dir.parent / "state" if state_dir is None else Path(state_dir)
    stamp = time.time() if now is None else now
    report: dict = {"removed": [], "kept": [], "busy": [], "failed": [], "skipped": None}
    if not results_dir.is_dir():
        report["skipped"] = "no results dir"
        return report
    if not _acquire_lock(results_dir, stamp):
        report["skipped"] = "locked"
        return report
    try:
        with os.scandir(results_dir) as entries:
            candidates = [Path(e.path) for e in entries
                          if e.name.startswith(SIGNAL_TASK_PREFIX)
                          and e.is_dir(follow_symlinks=False)]
        for task_dir in sorted(candidates):
            if stamp - _liveness(task_dir) <= LEASE_STALE_SEC:
                report["kept"].append(task_dir.name)
                continue
            try:
                lock_fd = _open_lease_lock(state_dir, task_dir.name)
            except OSError:
                report["busy"].append(task_dir.name)
                continue
            try:
                try:
                    fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                except BlockingIOError:
                    report["busy"].append(task_dir.name)
                    continue
                # Re-read the lease under the lock: a serve that landed first wins.
                lease = _lease_mtime(task_dir)
                if lease is not None and stamp - lease <= LEASE_STALE_SEC:
                    report["kept"].append(task_dir.name)
                    continue
                try:
                    shutil.rmtree(task_dir)
                except OSError as exc:
                    print(f"  [retention] could not remove {task_dir.name} "
                          f"({exc.__class__.__name__}); retrying next pass", file=sys.stderr)
                    report["failed"].append(task_dir.name)
                    continue
                if not _gone(task_dir):
                    print(f"  [retention] {task_dir.name} still present after rmtree; "
                          f"state kept, retrying next pass", file=sys.stderr)
                    report["failed"].append(task_dir.name)
                    continue
                _remove_serve_quota(state_dir, task_dir.name)
                report["removed"].append(task_dir.name)
            finally:
                os.close(lock_fd)
    finally:
        try:
            os.unlink(results_dir / LOCK_NAME)
        except OSError:
            pass
    return report


def run_hourly(results_dir, stop_event, *, interval: float = SWEEP_INTERVAL_SEC,
               archive_results=None, clock=time.time, state_dir=None) -> None:
    """Thread body: archive stale result texts, sweep task outputs, sleep, repeat."""
    while not stop_event.is_set():
        if archive_results is not None:
            try:
                archive_results()
            except Exception as exc:  # noqa: BLE001 — a failed pass must not end the loop
                print(f"  [retention] stale-result archive failed: {exc}", file=sys.stderr)
        try:
            sweep_task_outputs(results_dir, now=clock(), state_dir=state_dir)
        except Exception as exc:  # noqa: BLE001
            print(f"  [retention] task-output sweep failed: {exc}", file=sys.stderr)
        if stop_event.wait(interval):
            return
