"""Steady-state retention for Signal Room task-output dirs (R3).

`src/archive-stale-results.py` runs once at startup, so a long-lived host would
never reclaim `<results>/<task_id>/` dirs the generated-image capability creates.
agent-api therefore runs an hourly in-process sweep: it re-runs the startup
archiver's own `main()` for stale result texts, then ages out task-output dirs.

Liveness is a lease file (`<results>/<task_id>/.lease`) that every `/file-bytes`
serve touches. A dir is removed only once its lease — or, when no serve ever
happened, its newest mtime — is older than LEASE_STALE_SEC (26 h): strictly past
the daemon job's 24 h retry horizon plus its longest backoff, so generated bytes
survive every legitimate re-serve without job-side renewal. A lockfile keeps two
sweeps (threads or processes) from racing; the lease is re-read right before the
delete so a serve that lands mid-sweep wins.
"""

from __future__ import annotations

import os
import shutil
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from signal_room_tasks import SIGNAL_TASK_PREFIX  # noqa: E402

LEASE_NAME = ".lease"
LEASE_STALE_SEC = 26 * 3600
SWEEP_INTERVAL_SEC = 3600
LOCK_NAME = ".task-output-sweep.lock"
LOCK_STALE_SEC = 3600


def touch_lease(task_dir, now: float | None = None) -> None:
    """Mark `task_dir` live; called by the serving path on every authorized serve."""
    lease = Path(task_dir) / LEASE_NAME
    with open(lease, "a"):
        pass
    stamp = time.time() if now is None else now
    os.utime(lease, (stamp, stamp))


def _lease_mtime(task_dir: Path) -> float | None:
    try:
        return os.stat(task_dir / LEASE_NAME).st_mtime
    except OSError:
        return None


def _liveness(task_dir: Path) -> float:
    """Lease mtime when one exists; otherwise the newest mtime in the dir."""
    lease = _lease_mtime(task_dir)
    if lease is not None:
        return lease
    newest = os.lstat(task_dir).st_mtime
    try:
        with os.scandir(task_dir) as entries:
            for entry in entries:
                try:
                    newest = max(newest, entry.stat(follow_symlinks=False).st_mtime)
                except OSError:
                    continue
    except OSError:
        pass
    return newest


def _acquire_lock(results_dir: Path, now: float) -> bool:
    lock = results_dir / LOCK_NAME
    for _attempt in (1, 2):
        try:
            fd = os.open(lock, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            try:
                if now - os.stat(lock).st_mtime <= LOCK_STALE_SEC:
                    return False
                os.unlink(lock)
            except OSError:
                return False
            continue
        with os.fdopen(fd, "w") as fh:
            fh.write(str(os.getpid()))
        return True
    return False


def sweep_task_outputs(results_dir, now: float | None = None) -> dict:
    """One pass: remove abandoned `task-signal-*` dirs, keep live ones.

    Returns {"removed": [...], "kept": [...], "skipped": reason|None} with dir
    names, so a caller (or test) can see exactly what happened.
    """
    results_dir = Path(results_dir)
    stamp = time.time() if now is None else now
    report: dict = {"removed": [], "kept": [], "skipped": None}
    if not results_dir.is_dir():
        report["skipped"] = "no results dir"
        return report
    if not _acquire_lock(results_dir, stamp):
        report["skipped"] = "locked"
        return report
    try:
        with os.scandir(results_dir) as entries:
            candidates = [Path(e.path) for e in entries
                          if e.name.startswith(SIGNAL_TASK_PREFIX)
                          and e.is_dir(follow_symlinks=False)]
        for task_dir in sorted(candidates):
            if stamp - _liveness(task_dir) <= LEASE_STALE_SEC:
                report["kept"].append(task_dir.name)
                continue
            # Re-read the lease at the last moment: a serve mid-sweep must win.
            lease = _lease_mtime(task_dir)
            if lease is not None and stamp - lease <= LEASE_STALE_SEC:
                report["kept"].append(task_dir.name)
                continue
            shutil.rmtree(task_dir, ignore_errors=True)
            report["removed"].append(task_dir.name)
    finally:
        try:
            os.unlink(results_dir / LOCK_NAME)
        except OSError:
            pass
    return report


def run_hourly(results_dir, stop_event, *, interval: float = SWEEP_INTERVAL_SEC,
               archive_results=None, clock=time.time) -> None:
    """Thread body: archive stale result texts, sweep task outputs, sleep, repeat."""
    while not stop_event.is_set():
        if archive_results is not None:
            try:
                archive_results()
            except Exception as exc:  # noqa: BLE001 — a failed pass must not end the loop
                print(f"  [retention] stale-result archive failed: {exc}", file=sys.stderr)
        try:
            sweep_task_outputs(results_dir, now=clock())
        except Exception as exc:  # noqa: BLE001
            print(f"  [retention] task-output sweep failed: {exc}", file=sys.stderr)
        if stop_event.wait(interval):
            return
